#!/usr/bin/env python3
from __future__ import annotations

import html
import json
import re
import textwrap
from collections import defaultdict
from pathlib import Path
from typing import Iterable
from urllib.parse import urlparse

import requests
from bs4 import BeautifulSoup, Tag


ROOT = Path(__file__).resolve().parents[1]
CACHE_DIR = ROOT / ".cache"
CACHE_DIR.mkdir(exist_ok=True)

HOME_URL = "https://byteseismic.com/"
HOME_CACHE = CACHE_DIR / "byteseismic-home.html"
POSTS_CACHE = CACHE_DIR / "byteseismic-posts-with-content.json"

POSTS_API = "https://public-api.wordpress.com/rest/v1.1/sites/byteseismic.wordpress.com/posts/"
POST_FIELDS = "ID,slug,title,URL,date,excerpt,tags,content"
AUTO_MARKER = "<!-- AUTO-GENERATED BY scripts/build_archive.py -->"

SECTION_META = {
    "introduction": {
        "name": "Introduction",
        "summary": "Orientation pages that explain what philosophy is, why it matters, and how newcomers can enter the conversation without losing rigor.",
        "futureTags": ["orientation", "study-of-philosophy", "introductory-philosophy", "careers"],
        "preferredPath": "/introduction/what-is-philosophy/",
    },
    "philosophical-inquiry": {
        "name": "Philosophical Inquiry",
        "summary": "A branch devoted to the habits, dangers, and social conditions that make honest inquiry possible.",
        "futureTags": ["truth-seeking", "bias", "worldviews", "charitable-engagement"],
        "preferredPath": "/philosophical-inquiry/the-mindset-of-the-honest-seeker/",
    },
    "epistemology": {
        "name": "Epistemology",
        "summary": "Questions about belief, evidence, certainty, updating, and the tools we use to justify claims.",
        "futureTags": ["belief", "evidence", "bayes", "knowledge", "credence"],
        "preferredPath": "/epistemology/what-is-belief/",
    },
    "rational-thought": {
        "name": "Rational Thought",
        "summary": "Applied reasoning, fallacy detection, statistics, decision-making, and the emotional pressures that distort judgment.",
        "futureTags": ["logic", "fallacies", "decision-making", "statistics", "framing"],
        "preferredPath": "/rational-thought/categories-of-questions/",
    },
    "philosophy-of-science": {
        "name": "Philosophy of Science",
        "summary": "Method, explanation, induction, causation, and the standards that separate disciplined inquiry from pseudo-explanation.",
        "futureTags": ["science", "method", "induction", "causation", "falsifiability"],
        "preferredPath": "/philosophy-of-science/what-is-science/",
    },
    "philosophy-of-language": {
        "name": "Philosophy of Language",
        "summary": "How words, conventions, metaphors, and categories shape thought, agreement, and misunderstanding.",
        "futureTags": ["language", "semantics", "metaphor", "grammar", "equivocation"],
    },
    "philosophy-of-mind": {
        "name": "Philosophy of Mind",
        "summary": "Consciousness, cognition, free will, psychology, and the overlap between first-person experience and third-person analysis.",
        "futureTags": ["consciousness", "cognition", "free-will", "neuroscience", "subjectivity"],
        "preferredPath": "/philosophy-of-mind/where-consciousness-can-must-emerge/",
    },
    "metaphysics": {
        "name": "Metaphysics",
        "summary": "Reality, causation, emergence, nihilism, dualism, and the limits of what can be said to exist.",
        "futureTags": ["reality", "emergence", "materialism", "dualism", "nihilism"],
    },
    "ethics": {
        "name": "Ethics",
        "summary": "Moral language, meta-ethics, culpability, applied dilemmas, and the challenge of moving from values to action.",
        "futureTags": ["ethics", "meta-ethics", "culpability", "moral-realism", "human-rights"],
    },
    "humanistic-philosophies": {
        "name": "Humanistic Philosophies",
        "summary": "Meaning, religion, stoicism, existentialism, and the existential project of becoming a more lucid human being.",
        "futureTags": ["meaning", "stoicism", "existentialism", "religion", "human-nature"],
        "preferredPath": "/humanistic-philosophies/stoicism-key-concepts/",
    },
    "economics": {
        "name": "Economics",
        "summary": "Economic concepts, schools of thought, incentives, risk, entitlements, and the effects of AI on work and prosperity.",
        "futureTags": ["economics", "incentives", "risk", "public-policy", "future-of-work"],
    },
    "philosophy-of-ai": {
        "name": "Philosophy of AI",
        "summary": "Truthfulness, prompting, capabilities, bias, public discourse, and the implications of dialoguing with machine systems.",
        "futureTags": ["ai", "prompting", "alignment", "bias", "public-discourse"],
        "preferredPath": "/philosophy-of-ai/assessing-ai-alignment-with-truth/",
    },
    "political-philosophy": {
        "name": "Political Philosophy",
        "summary": "Collective life, legitimacy, identity, tribal division, electoral systems, and the structures that stabilize or degrade public reason.",
        "futureTags": ["politics", "social-contract", "identity", "institutions", "public-trust"],
    },
    "philosophers": {
        "name": "Philosophers",
        "summary": "Author-centered pathways through major traditions, often including dialogue pages, charted summaries, and grouped schools.",
        "futureTags": ["socrates", "plato", "hume", "kant", "nietzsche"],
        "preferredPath": "/philosophers/dialoguing-with-epictetus/",
    },
    "miscellany": {
        "name": "Miscellany",
        "summary": "A flexible branch for adjacent domains such as axiology, history, complexity, information theory, and cross-disciplinary side paths.",
        "futureTags": ["aesthetics", "history", "complexity", "information", "wisdom"],
    },
}

SECTION_IDS = tuple(SECTION_META.keys())
GROUP_PAGE_TITLES = {
    "Site Map": "/menu-structure/",
    "Recent Posts — Expanded Version": "/recent-posts-expanded-version/",
}
FEATURED_PAGE_SPECS = [
    {
        "title": "What Is Philosophy?",
        "section_id": "introduction",
        "path": "/introduction/what-is-philosophy/",
    },
    {
        "title": "What Is Truth?",
        "section_id": "philosophical-inquiry",
        "path": "/philosophical-inquiry/what-is-truth/",
    },
    {
        "title": "The Mindset of the Honest Seeker",
        "section_id": "philosophical-inquiry",
        "path": "/philosophical-inquiry/the-mindset-of-the-honest-seeker/",
    },
    {
        "title": "What Is Belief?",
        "section_id": "epistemology",
        "path": "/epistemology/what-is-belief/",
    },
    {
        "title": "What Is Science?",
        "section_id": "philosophy-of-science",
        "path": "/philosophy-of-science/what-is-science/",
    },
    {
        "title": "Where Consciousness Can & Must Emerge",
        "section_id": "philosophy-of-mind",
        "path": "/philosophy-of-mind/where-consciousness-can-must-emerge/",
    },
    {
        "title": "Assessing AI Alignment with Truth",
        "section_id": "philosophy-of-ai",
        "path": "/philosophy-of-ai/assessing-ai-alignment-with-truth/",
    },
    {
        "title": "Categories of Questions",
        "section_id": "rational-thought",
        "path": "/rational-thought/categories-of-questions/",
    },
    {
        "title": "Stoicism: Key Concepts",
        "section_id": "humanistic-philosophies",
        "path": "/humanistic-philosophies/stoicism-key-concepts/",
    },
    {
        "title": "Dialoguing with Epictetus",
        "section_id": "philosophers",
        "path": "/philosophers/dialoguing-with-epictetus/",
    },
    {
        "title": "Dialoguing with Aquinas",
        "section_id": "philosophers",
        "path": "/philosophers/dialoguing-with-aquinas/",
    },
    {
        "title": "Dialoguing with Quine",
        "section_id": "philosophers",
        "path": "/philosophers/dialoguing-with-quine/",
    },
    {
        "title": "Dialoguing with Merleau-Ponty",
        "section_id": "philosophers",
        "path": "/philosophers/dialoguing-with-merleau-ponty/",
    },
]
FEATURED_PATHS_BY_TITLE = {
    spec["title"].lower(): (spec["section_id"], spec["path"]) for spec in FEATURED_PAGE_SPECS
}

CLASSIFIER_KEYWORDS = {
    "introduction": {"philosophy", "careers", "maturity", "argumentative", "studying", "education"},
    "philosophical-inquiry": {"truth", "worldview", "ideology", "inquiry", "seeker", "minds", "bias", "dogma", "charitable"},
    "epistemology": {"belief", "knowledge", "evidence", "doubt", "faith", "bayes", "credence", "epistem"},
    "rational-thought": {"rational", "fallacy", "statistics", "question", "logic", "game theory", "design thinking", "science denial", "futurism", "rationality"},
    "philosophy-of-science": {"science", "induction", "deduction", "falsifiability", "pseudoscience", "explanation", "causation", "etiology", "forensic"},
    "philosophy-of-language": {"language", "etymology", "semantics", "metaphor", "grammar", "word", "terms"},
    "philosophy-of-mind": {"mind", "consciousness", "free will", "thought", "neuroscience", "psychology", "cognition", "neuro"},
    "metaphysics": {"metaphysics", "ontology", "reality", "emergence", "nihilism", "dualism", "materialism", "time", "being"},
    "ethics": {"ethics", "morality", "axiology", "meta-ethics", "moral", "rights", "culpability", "suicide", "trolley"},
    "humanistic-philosophies": {"stoicism", "existential", "religion", "meaning", "human", "insignificance", "pragmatism", "life"},
    "economics": {"economics", "market", "capital", "wage", "ubi", "income", "wealth", "workweek", "trade"},
    "philosophy-of-ai": {"ai", "llm", "model", "chatgpt", "prompt", "alignment", "grok", "artificial intelligence", "intelligence"},
    "political-philosophy": {"politic", "electoral", "social contract", "democracy", "identity", "citizen", "state"},
    "philosophers": {
        "dialoguing",
        "charting",
        "philosophers",
        "stoics",
        "rationalists",
        "empiricists",
        "existentialists",
        "plato",
        "aristotle",
        "kant",
        "hume",
        "aquinas",
        "marcus aurelius",
    },
}

BRANCH_PROFILES = {
    "philosophical-inquiry": {
        "standfirst": "truth-seeking as a discipline of attention, self-suspicion, and charitable pressure.",
        "lens": "whether a mind is becoming more answerable to reality or merely more fluent in defending itself",
        "stakes": "Honest inquiry is fragile because it asks people to expose their favorite beliefs to better evidence, rival interpretations, and the possibility of revision.",
        "pressure": "The central danger is not only error. It is the comfortable merger of identity, tribe, and certainty, where a person begins protecting a self-image while thinking they are protecting truth.",
        "route": "A good route through this branch is to ask what each page is trying to rescue: intellectual humility, evidential patience, conceptual charity, or courage under disagreement.",
        "items": ["The belief being protected", "The evidence being avoided", "The social reward for certainty", "The better question that would reopen inquiry"],
    },
    "epistemology": {
        "standfirst": "belief, justification, uncertainty, and the standards by which claims become responsible.",
        "lens": "what would make a belief worth holding, revising, or abandoning",
        "stakes": "Epistemology matters because it gives the archive a standard for responsible confidence. It asks how perception, testimony, inference, memory, and probability should constrain belief.",
        "pressure": "The recurring pressure is false certainty: treating a feeling of obviousness, a social consensus, or a useful assumption as if it had already earned the status of knowledge.",
        "route": "The best route is to track how evidence changes credence, how justification differs from psychological comfort, and how skepticism can discipline thought without paralyzing it.",
        "items": ["Belief and knowledge", "Evidence and justification", "Credence and updating", "Skepticism without paralysis"],
    },
    "rational-thought": {
        "standfirst": "reasoning habits, fallacies, statistics, and the practical discipline of thinking under pressure.",
        "lens": "how a person can reason better when incentives, emotions, and framing effects are pushing the other way",
        "stakes": "Rational thought is the applied workshop of the archive. It tests whether philosophical care can survive ordinary argument, public controversy, bad statistics, and misleading frames.",
        "pressure": "The danger is performative rationality: naming fallacies, probabilities, or methods while using them as badges rather than tools for better judgment.",
        "route": "A useful path through this branch is practical. Ask what mistake the page helps detect, what habit it trains, and what kind of disagreement it makes less confused.",
        "items": ["The reasoning error", "The tempting shortcut", "The corrective habit", "The better standard of comparison"],
    },
    "ethics": {
        "standfirst": "moral language, value, realism, non-realism, obligation, and the hard work of justification.",
        "lens": "what moral claims are claiming, what could make them true or binding, and what follows if they are not",
        "stakes": "Ethics is high-value because it forces the archive to distinguish moral feeling, social practice, objective obligation, and practical recommendation without pretending those differences are easy.",
        "pressure": "The live pressure includes moral realism, moral non-realism, divine command theory, human rights language, and the risk of smuggling an ought into premises that only describe what is.",
        "route": "The best route is to keep three questions apart: what people value, what a moral sentence means, and what could justify a demand on another person.",
        "items": ["Moral realism and anti-realism", "The is/ought gap", "Normativity and motivation", "Rights, duties, and value"],
    },
    "philosophy-of-ai": {
        "standfirst": "machine reasoning, prompting, truth-alignment, public trust, and the ethics of human-machine dialogue.",
        "lens": "what changes when a machine system becomes a partner in reasoning rather than a passive tool",
        "stakes": "Philosophy of AI matters here because the archive itself is built through human-machine dialogue. The branch therefore has to examine truthfulness, agency, prompting, bias, and responsibility from the inside.",
        "pressure": "The danger is misplaced authority: either dismissing AI outputs because they are synthetic, or treating fluent synthesis as if it already carried understanding, evidence, or accountability.",
        "route": "A strong route through this branch asks what the model is doing, what the human is doing, and where the final responsibility for judgment belongs.",
        "items": ["Truthfulness and hallucination", "Prompting as epistemic design", "Model bias and user bias", "Human responsibility for final judgment"],
    },
    "philosophers": {
        "standfirst": "philosophers as voices, methods, schools, and durable provocations rather than as name-only entries.",
        "lens": "what survives when a thinker is treated as a living method of inquiry instead of a summary label",
        "stakes": "The philosophers branch is strongest when it preserves voice, context, and method. A thinker should not be flattened into a doctrine if the style of thinking is part of the contribution.",
        "pressure": "The pressure is canon without encounter: turning philosophers into monuments, slogans, or quick alignments instead of letting their arguments and temperaments disturb the reader.",
        "route": "A good route is to move from school to figure to dialogue to chart, so the reader sees both the tradition and the individual pressure each thinker applies.",
        "items": ["The figure's central pressure", "The method or style of argument", "The strongest internal tension", "The modern question the figure still sharpens"],
    },
}

DEFAULT_PROFILE = {
    "standfirst": "the core distinctions, tensions, and future paths that make the topic worth reconstructing.",
    "lens": "what the topic clarifies and what it asks the reader to hold apart",
    "stakes": "This topic matters because it organizes a cluster of questions that become harder to handle when they are compressed into a slogan.",
    "pressure": "The main pressure comes from treating a useful distinction as final, or treating a local insight as if it solved more than it actually solves.",
    "route": "A good route is to identify the strongest version of the idea, then test where it needs qualification, evidence, or a neighboring concept.",
    "items": ["The central distinction", "The strongest charitable version", "The main pressure point", "The neighboring question"],
}

TOPIC_ITEMS = {
    "Dangers to Honest Inquiry": [
        "Cognitive bias as self-protection",
        "Ideological siloing",
        "Explanatory depth illusions",
        "Emotional certainty mistaken for evidence",
    ],
    "Meta-Ethics": [
        "Moral realism and moral non-realism",
        "Moral language and meaning",
        "The is/ought gap",
        "Normativity, motivation, and obligation",
    ],
    "Precision Prompting": [
        "Task framing and constraints",
        "Examples, counterexamples, and format discipline",
        "Iterative refinement and verification",
        "Human responsibility for final judgment",
    ],
    "Stoics": [
        "Virtue as the stable good",
        "Assent, impressions, and judgment",
        "Control, fate, and disciplined desire",
        "Cosmopolitan duty and inner freedom",
    ],
    "Avoiding Logical Fallacies": [
        "The structure of the argument",
        "The tempting rhetorical shortcut",
        "The charitable correction",
        "The difference between naming a fallacy and explaining the reasoning error",
    ],
}

TOPIC_ALIASES = {
    "Stoics": "Stoicism",
    "Rationalists": "Rationalism",
    "Empiricists": "Empiricism",
    "Existentialists": "Existentialism",
    "Phenomenologists": "Phenomenology",
    "Pragmatists": "Pragmatism",
    "Scholastics": "Scholasticism",
    "Critical Theorists": "Critical Theory",
}

LOW_VALUE_HEADING_PATTERNS = (
    "table of contents",
    "quiz",
    "answers",
    "discussion questions",
    "discussion prompts",
)
LOW_VALUE_PROMPT_PATTERNS = (
    "quiz",
    "answers at the end",
    "discussion questions",
    "provide 12 discussion",
    "sources of content",
    "table of contents",
    "does this make sense",
)
PROMPT_STARTERS = (
    "provide",
    "produce",
    "list",
    "identify",
    "create",
    "write",
    "imagine",
    "what",
    "how",
    "why",
    "can",
    "should",
    "is",
    "are",
    "does",
    "explain",
    "elaborate",
    "trace",
    "chart",
    "comment",
    "weigh",
    "for each",
    "allow me",
    "i am",
)
DATE_URL_RE = re.compile(r"/\d{4}/\d{2}/\d{2}/([^/?#]+)/?$")
NUMBER_PREFIX_RE = re.compile(r"^\s*\d+[\.\)]\s*")
LI_LINK_RE = re.compile(r"<li>\s*<a[^>]+href=\"([^\"]*)\"[^>]*>(.*?)</a>", re.IGNORECASE)


def clean_text(value: str | None) -> str:
    if not value:
        return ""
    text = html.unescape(value)
    text = text.replace("\xa0", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def canonical_url(url: str) -> str:
    parsed = urlparse(url)
    path = parsed.path.rstrip("/") or "/"
    return f"https://byteseismic.com{path}"


def slug_from_url(url: str) -> str | None:
    match = DATE_URL_RE.search(url)
    if match:
        return match.group(1)
    parsed = urlparse(url)
    bits = [bit for bit in parsed.path.split("/") if bit]
    if bits:
        return bits[-1]
    return None


def slugify(text: str) -> str:
    lowered = clean_text(text).lower()
    lowered = lowered.replace("&", " and ")
    lowered = re.sub(r"[“”\"'`]+", "", lowered)
    lowered = re.sub(r"[^a-z0-9]+", "-", lowered)
    lowered = lowered.strip("-")
    return lowered or "untitled"


def strip_html(raw: str) -> str:
    return clean_text(BeautifulSoup(raw or "", "html.parser").get_text(" ", strip=True))


def strip_number_prefix(text: str) -> str:
    return NUMBER_PREFIX_RE.sub("", clean_text(text))


def looks_like_prompt(text: str) -> bool:
    cleaned = strip_number_prefix(text)
    lowered = cleaned.lower()
    return "?" in cleaned or lowered.startswith(PROMPT_STARTERS)


def fetch_homepage_html() -> str:
    if HOME_CACHE.exists():
        return HOME_CACHE.read_text()
    response = requests.get(HOME_URL, timeout=30)
    response.raise_for_status()
    HOME_CACHE.write_text(response.text)
    return response.text


def fetch_posts(cache_path: Path, fields: str) -> list[dict]:
    if cache_path.exists():
        return json.loads(cache_path.read_text())

    session = requests.Session()
    offset = 0
    posts: list[dict] = []
    total_found = None

    while True:
        url = f"{POSTS_API}?number=100&offset={offset}&fields={fields}"
        response = session.get(url, timeout=60)
        response.raise_for_status()
        data = response.json()
        batch = data.get("posts", [])
        posts.extend(batch)
        total_found = total_found or data.get("found")
        if not batch or len(posts) >= (total_found or 0):
            break
        offset += len(batch)

    cache_path.write_text(json.dumps(posts, indent=2, ensure_ascii=False))
    return posts


def fetch_all_posts() -> list[dict]:
    return fetch_posts(POSTS_CACHE, POST_FIELDS)


def parse_topic_list(ul: Tag) -> list[dict]:
    nodes = []
    for li in ul.find_all("li", recursive=False):
        anchor = li.find("a", recursive=False) or li.find("a")
        title = clean_text(anchor.get_text(" ", strip=True) if anchor else li.get_text(" ", strip=True))
        href = clean_text(anchor.get("href")) if anchor and anchor.get("href") else ""
        child_ul = li.find("ul", recursive=False)
        children = parse_topic_list(child_ul) if child_ul else []
        nodes.append({"title": title, "href": href, "children": children})
    return nodes


def parse_malformed_topic_html(raw_html: str) -> list[dict]:
    prepared = (
        raw_html.replace("<ul", "\n<ul")
        .replace("</ul>", "\n</ul>\n")
        .replace("<li>", "\n<li>")
    )
    root: list[dict] = []
    stack: list[list[dict]] = [root]

    for line in prepared.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("<ul"):
            current = stack[-1]
            if current:
                current[-1].setdefault("children", [])
                stack.append(current[-1]["children"])
            else:
                stack.append(current)
            continue
        if stripped.startswith("</ul"):
            if len(stack) > 1:
                stack.pop()
            continue
        match = LI_LINK_RE.search(stripped)
        if match:
            href = clean_text(match.group(1))
            title = clean_text(BeautifulSoup(match.group(2), "html.parser").get_text(" ", strip=True))
            stack[-1].append({"title": title, "href": href, "children": []})

    return root


def is_anchor_only(href: str, heading_id: str) -> bool:
    return bool(href and f"#{heading_id}" in href)


def parse_detail_nodes(detail: Tag, section_id: str, heading_id: str) -> list[dict]:
    summary_tag = detail.find("summary")
    summary = clean_text(summary_tag.get_text(" ", strip=True) if summary_tag else "")
    nodes = parse_malformed_topic_html(str(detail))
    if not nodes:
        return []

    if summary.lower() == "toggle section on/off":
        if (
            nodes
            and nodes[0]["title"].upper() == SECTION_META[section_id]["name"].upper()
            and nodes[0].get("children")
        ):
            nodes = nodes[0]["children"]

        filtered = []
        for node in nodes:
            same_section = node["title"].upper() == SECTION_META[section_id]["name"].upper()
            anchor_only = is_anchor_only(node.get("href", ""), heading_id)
            if same_section and anchor_only:
                continue
            filtered.append(node)
        return filtered

    root = nodes[0]
    if root.get("children"):
        href = root.get("href", "")
        title = summary or root["title"]
        return [
            {
                "title": title,
                "href": "" if is_anchor_only(href, heading_id) else href,
                "children": root["children"],
            }
        ]

    return [{"title": summary or root["title"], "href": "", "children": nodes}]


def section_nodes_from_home(html_text: str) -> dict[str, list[dict]]:
    soup = BeautifulSoup(html_text, "html.parser")
    sections: dict[str, list[dict]] = {}
    for heading in soup.select("h4[id]"):
        section_id = heading["id"].lower()
        if section_id not in SECTION_META:
            continue
        details = []
        for element in heading.next_elements:
            if isinstance(element, Tag) and element.name == "h4" and element is not heading and element.get("id"):
                break
            if isinstance(element, Tag) and element.name == "details":
                details.append(element)

        if not details:
            continue

        nodes: list[dict] = []
        for detail in details:
            nodes.extend(parse_detail_nodes(detail, section_id, heading["id"]))
        sections[section_id] = nodes
    return sections


def flatten_titles(nodes: Iterable[dict]) -> list[str]:
    titles: list[str] = []
    for node in nodes:
        titles.append(node["title"])
        titles.extend(flatten_titles(node.get("children", [])))
    return titles


def hierarchy_lookup(nodes: list[dict], section_id: str, parents: list[str] | None = None) -> dict[str, dict]:
    parents = parents or []
    lookup: dict[str, dict] = {}
    for node in nodes:
        href = node.get("href", "")
        title = node["title"]
        if href and "byteseismic.com" in href and not href.endswith("/feed/"):
            lookup[canonical_url(href)] = {
                "section_id": section_id,
                "parents": parents[:],
                "title": title,
            }
        lookup.update(hierarchy_lookup(node.get("children", []), section_id, parents + [title]))
    return lookup


def classify_section(post: dict) -> str:
    title = clean_text(post.get("title"))
    excerpt = strip_html(post.get("excerpt", ""))
    tag_blob = " ".join(clean_text(tag_name) for tag_name in (post.get("tags") or {}).keys())
    corpus = f"{title} {excerpt} {tag_blob}".lower()

    best_section = "miscellany"
    best_score = 0
    for section_id, keywords in CLASSIFIER_KEYWORDS.items():
        score = sum(1 for keyword in keywords if keyword in corpus)
        if score > best_score:
            best_score = score
            best_section = section_id
    return best_section


def build_path_for_node(section_id: str, title: str, source_url: str = "", synthetic: bool = False) -> str:
    if title in GROUP_PAGE_TITLES:
        return GROUP_PAGE_TITLES[title]
    slug = slug_from_url(source_url) if source_url and not synthetic else None
    slug = slug or slugify(title)
    return f"/{section_id}/{slug}/"


def normalize_heading_list(content_html: str, title: str) -> tuple[list[str], list[str], list[str]]:
    soup = BeautifulSoup(content_html or "", "html.parser")
    root = soup.select_one(".entry-content") or soup.select_one(".wp-block-post-content") or soup

    headings: list[str] = []
    paragraphs: list[str] = []

    for heading in root.select("h1, h2, h3, h4"):
        text = strip_number_prefix(heading.get_text(" ", strip=True))
        lowered = text.lower()
        if not text or lowered == clean_text(title).lower():
            continue
        if any(pattern in lowered for pattern in LOW_VALUE_HEADING_PATTERNS):
            continue
        if text not in headings:
            headings.append(text)

    for paragraph in root.select("p"):
        text = clean_text(paragraph.get_text(" ", strip=True))
        lowered = text.lower()
        if not text or "table of contents" in lowered:
            continue
        if len(text) < 70:
            continue
        paragraphs.append(text)

    prompt_like = []
    thread_like = []
    for heading in headings:
        if looks_like_prompt(heading):
            prompt_like.append(heading)
        else:
            thread_like.append(heading)
    return prompt_like[:8], thread_like[:16], paragraphs[:5]


def sentence_split(text: str) -> list[str]:
    cleaned = clean_text(text)
    if not cleaned:
        return []
    return [
        sentence.strip()
        for sentence in re.split(r"(?<=[.!?])\s+(?=[A-Z“\"'(])", cleaned)
        if len(sentence.strip()) >= 35
    ]


def compact_text(text: str, limit: int = 310) -> str:
    cleaned = clean_text(text)
    if len(cleaned) <= limit:
        return cleaned
    clipped = cleaned[:limit].rsplit(" ", 1)[0].rstrip(" ,;:")
    return f"{clipped}."


def is_low_value_heading(text: str) -> bool:
    lowered = clean_text(text).lower()
    if lowered in {"questions", "answers", "conclusion"}:
        return True
    return any(pattern in lowered for pattern in LOW_VALUE_HEADING_PATTERNS)


def heading_level(tag: Tag) -> int:
    if tag.name and re.fullmatch(r"h[1-6]", tag.name):
        return int(tag.name[1])
    return 6


def source_root(content_html: str) -> Tag | BeautifulSoup:
    soup = BeautifulSoup(content_html or "", "html.parser")
    return soup.select_one(".entry-content") or soup.select_one(".wp-block-post-content") or soup


def fragment_from_href(href: str) -> str:
    if not href or "#" not in href:
        return ""
    return href.rsplit("#", 1)[-1].strip()


def toc_prompt_heading_ids(root: Tag | BeautifulSoup) -> list[str]:
    best_ids: list[str] = []
    best_score = 0

    for ordered_list in root.find_all("ol"):
        direct_items = ordered_list.find_all("li", recursive=False)
        if len(direct_items) < 2:
            continue

        ids: list[str] = []
        score = 0
        for item in direct_items:
            anchor = item.find("a", recursive=False)
            if anchor is None:
                continue
            text = strip_number_prefix(anchor.get_text(" ", strip=True))
            href = clean_text(anchor.get("href"))
            fragment = fragment_from_href(href)
            if not fragment or is_low_value_prompt(text):
                continue
            if looks_like_prompt(text):
                score += 2
            elif len(text) >= 70:
                score += 1
            else:
                continue
            ids.append(fragment)

        if score > best_score and len(ids) >= 2:
            best_score = score
            best_ids = ids

    return dedupe(best_ids)[:8]


def source_prompt_heading_tags(content_html: str, title: str) -> list[Tag]:
    root = source_root(content_html)
    headings_by_id = {
        clean_text(heading.get("id")): heading
        for heading in root.find_all(re.compile(r"^h[1-6]$"))
        if heading.get("id")
    }
    toc_ids = toc_prompt_heading_ids(root)
    if toc_ids:
        toc_headings = []
        for heading_id in toc_ids:
            heading = headings_by_id.get(heading_id)
            if heading is None:
                continue
            text = strip_number_prefix(heading.get_text(" ", strip=True))
            if not text or is_low_value_heading(text) or is_low_value_prompt(text):
                continue
            toc_headings.append(heading)
        if toc_headings:
            return toc_headings[:5]

    headings: list[Tag] = []
    seen = set()
    for heading in root.find_all(re.compile(r"^h[1-6]$")):
        text = strip_number_prefix(heading.get_text(" ", strip=True))
        lowered = text.lower()
        if not text or lowered == clean_text(title).lower():
            continue
        if is_low_value_heading(text):
            continue
        if not looks_like_prompt(text) or is_low_value_prompt(text):
            continue
        normalized = re.sub(r"[^a-z0-9]+", " ", text.lower()).strip()
        if normalized in seen:
            continue
        seen.add(normalized)
        headings.append(heading)
    return headings[:5]


def split_label(text: str) -> tuple[str, str]:
    cleaned = clean_text(text)
    if ":" not in cleaned:
        return "", cleaned
    label, body = cleaned.split(":", 1)
    label = strip_number_prefix(label).strip(" -–")
    body = body.strip()
    if not label or len(label) > 92 or len(body) < 20:
        return "", cleaned
    return label, body


def rewrite_source_sentence(text: str) -> str:
    cleaned_full = clean_text(text)
    if cleaned_full.startswith(("“", '"')):
        sentence = cleaned_full
    else:
        sentences = sentence_split(cleaned_full)
        sentence = sentences[0] if sentences else cleaned_full
    label, body = split_label(sentence)
    if label and body:
        sentence = body
    replacements = [
        (r"^Yes,\s*", ""),
        (r"^Certainly,\s*", ""),
        (r"^Overall,\s*", ""),
        (r"^In essence,\s*", ""),
        (r"\b[Yy]our pushback\b", "the pushback"),
        (r"\b[Yy]our position\b", "the curator’s position"),
        (r"\b[Yy]our perspective\b", "the position"),
        (r"\b[Yy]our point\b", "the point"),
        (r"\b[Yy]our argument\b", "the argument"),
        (r"\b[Yy]ou argue that\b", "the argument holds that"),
        (r"\b[Yy]ou argue\b", "the argument holds"),
        (r"\b[Yy]ou acknowledge\b", "the position acknowledges"),
        (r"\b[Yy]ou highlight\b", "the position highlights"),
        (r"\b[Yy]ou said\b", "the earlier formulation said"),
        (r"\b[Ll]et’s\b", "the response can"),
    ]
    for pattern, replacement in replacements:
        sentence = re.sub(pattern, replacement, sentence)
    sentence = re.sub(r"\s+([.,;:!?])", r"\1", sentence)
    sentence = re.sub(r"([.!?][”\"])\.", r"\1", sentence)
    sentence = compact_text(sentence, 280).strip()
    if sentence:
        sentence = sentence[0].upper() + sentence[1:]
    closed_quote_punctuation = sentence.endswith((".”", "!”", "?”", '."', '!"', '?"'))
    if sentence and sentence[-1] not in ".!?" and not closed_quote_punctuation:
        sentence += "."
    return sentence


def extract_source_prompt_details(content_html: str, title: str) -> list[dict]:
    root = source_root(content_html)
    accepted_headings = source_prompt_heading_tags(content_html, title)
    if not accepted_headings:
        return []

    details: list[dict] = []
    for index, prompt_heading in enumerate(accepted_headings):
        next_prompt_heading = accepted_headings[index + 1] if index + 1 < len(accepted_headings) else None
        children: list[dict] = []
        paragraphs: list[str] = []
        items: list[str] = []
        current_child: dict | None = None

        for element in prompt_heading.next_elements:
            if element is prompt_heading:
                continue
            if next_prompt_heading is not None and element is next_prompt_heading:
                break
            if not isinstance(element, Tag):
                continue

            if element.name and re.fullmatch(r"h[1-6]", element.name):
                text = strip_number_prefix(element.get_text(" ", strip=True))
                if not text or text == strip_number_prefix(prompt_heading.get_text(" ", strip=True)):
                    continue
                if (
                    looks_like_prompt(text)
                    and is_low_value_prompt(text)
                    and heading_level(element) <= heading_level(prompt_heading)
                ):
                    break
                if looks_like_prompt(text) and not is_low_value_prompt(text):
                    continue
                if is_low_value_heading(text) or is_low_value_prompt(text):
                    continue
                current_child = {"title": text, "level": heading_level(element), "paragraphs": [], "items": []}
                children.append(current_child)
                continue

            if element.name == "p":
                text = clean_text(element.get_text(" ", strip=True))
                lowered = text.lower()
                if len(text) < 65 or "table of contents" in lowered:
                    continue
                target = current_child["paragraphs"] if current_child is not None else paragraphs
                target.append(text)
                continue

            if element.name == "li":
                text = clean_text(element.get_text(" ", strip=True))
                if len(text) < 45 or is_low_value_prompt(text):
                    continue
                target = current_child["items"] if current_child is not None else items
                target.append(text)

        useful_children = []
        for child in children:
            if child["paragraphs"] or child["items"]:
                child["paragraphs"] = child["paragraphs"][:4]
                child["items"] = child["items"][:6]
                useful_children.append(child)

        details.append(
            {
                "prompt": clarify_prompt(prompt_heading.get_text(" ", strip=True)),
                "paragraphs": paragraphs[:4],
                "items": items[:8],
                "children": useful_children[:8],
            }
        )

    return details


def dedupe(items: Iterable[str]) -> list[str]:
    seen = set()
    result = []
    for item in items:
        if item and item not in seen:
            result.append(item)
            seen.add(item)
    return result


def branch_profile(section_id: str) -> dict:
    return BRANCH_PROFILES.get(section_id, DEFAULT_PROFILE)


def is_low_value_prompt(text: str) -> bool:
    lowered = clean_text(text).lower()
    return any(pattern in lowered for pattern in LOW_VALUE_PROMPT_PATTERNS)


def clarify_prompt(text: str) -> str:
    prompt = strip_number_prefix(text).strip(" :-")
    prompt = re.sub(r"\bthe entire thread above\b", "this discussion", prompt, flags=re.IGNORECASE)
    prompt = re.sub(r"\bthe discussion above\b", "this discussion", prompt, flags=re.IGNORECASE)
    prompt = re.sub(r"\bcontent above\b", "this discussion", prompt, flags=re.IGNORECASE)
    prompt = re.sub(r"\bthread above\b", "this discussion", prompt, flags=re.IGNORECASE)
    if prompt:
        prompt = prompt[0].upper() + prompt[1:]
    return prompt


def curated_source_prompts(page: dict) -> list[str]:
    prompts = []
    for prompt in page.get("source_prompts", []):
        clarified = clarify_prompt(prompt)
        if not clarified or is_low_value_prompt(clarified):
            continue
        normalized = re.sub(r"[^a-z0-9]+", " ", clarified.lower()).strip()
        if any(normalized and normalized in re.sub(r"[^a-z0-9]+", " ", existing.lower()) for existing in prompts):
            continue
        prompts.append(clarified)
    return dedupe(prompts)[:5]


def topic_label(title: str) -> str:
    cleaned = clean_text(title)
    if cleaned in TOPIC_ALIASES:
        return TOPIC_ALIASES[cleaned]
    patterns = [
        r"^What is\s+",
        r"^What are\s+",
        r"^Dialoguing with\s+",
        r"^Charting\s+",
        r"^Dangers:\s+",
        r"^Case #\d+\s*[-–]\s*",
    ]
    for pattern in patterns:
        cleaned = re.sub(pattern, "", cleaned, flags=re.IGNORECASE)
    return cleaned.strip(" ?")


def infer_kind(title: str, has_children: bool) -> str:
    lowered = clean_text(title).lower()
    if title in GROUP_PAGE_TITLES:
        return "special"
    if lowered.startswith("dialoguing with "):
        return "dialogue"
    if lowered.startswith("charting "):
        return "chart"
    if lowered.startswith("dangers:"):
        return "danger"
    if "core concepts" in lowered:
        return "core"
    if lowered.startswith("what is ") or lowered.startswith("what are "):
        return "concept"
    if has_children:
        return "cluster"
    if " vs " in lowered or " and " in lowered or "&" in title:
        return "comparison"
    return "essay"


def tag_candidates(page: dict, section_meta: dict) -> list[str]:
    base = [slugify(word) for word in re.split(r"[\s/&:—–-]+", topic_label(page["title"])) if len(word) > 3]
    tags = dedupe(base + list(section_meta["futureTags"]))
    return tags[:5]


def generic_standfirst(page: dict, section_meta: dict) -> str:
    topic = topic_label(page["title"])
    kind = page["kind"]
    profile = branch_profile(page["section_id"])
    if kind == "dialogue":
        return f"A reconstructed philosopher page on {topic}, keeping the voice, tensions, and main lines of argument in clearer prose."
    if kind == "chart":
        return f"A reconstructed chart page on {topic}, mapping the main alignments, fault lines, and enduring contributions."
    if kind == "danger":
        return f"A reconstructed cautionary page on {topic}, clarifying the appeal of the pattern and the epistemic costs it can impose."
    if kind == "cluster":
        return f"A reconstructed branch page on {topic}, placing its nested posts inside {profile['standfirst']}"
    return f"A reconstructed {section_meta['name'].lower()} page on {topic}, centered on {profile['standfirst']}"


def feature_summary(page: dict, section_meta: dict) -> str:
    topic = topic_label(page["title"])
    if page["kind"] == "dialogue":
        return f"A guided reconstruction of {topic} that keeps the philosopher’s voice, major claims, and main points of resistance in view."
    if page["kind"] == "chart":
        return f"A terrain map of {topic}, showing which themes, alignments, and tensions define the wider philosophical landscape."
    if page["kind"] == "danger":
        return f"A cautionary essay on {topic}, treating it as a recurring distortion that can quietly damage serious inquiry."
    return f"A reconstructed page on {topic}, written to clarify its role inside the {section_meta['name'].lower()} branch."


def prompt_pack(page: dict, section_meta: dict) -> list[tuple[str, str]]:
    topic = page["title"]
    subject = topic_label(topic)
    source_prompts = curated_source_prompts(page)
    if source_prompts and page["kind"] not in {"dialogue", "chart"}:
        return [(f"prompt-{index}", prompt) for index, prompt in enumerate(source_prompts, start=1)]
    if page["kind"] == "dialogue":
        philosopher = subject
        return [
            ("voice-fragment", f"Preserve whatever in {philosopher}'s voice, cadence, or method becomes thinner when reduced to neutral exposition."),
            ("beginner-dialogue", f"Imagine a dialogue between {philosopher} and a bright beginner curious about the core of the view."),
            ("deeper-dialogue", f"Imagine a dialogue between {philosopher} and a philosophically serious interlocutor probing the structure of the view."),
            ("critical-dialogue", f"Imagine a dialogue between {philosopher} and a critic pressing on the most vulnerable points."),
            ("five-notions", f"Identify several of {philosopher}'s most enduring ideas and estimate their standing today."),
        ]
    if page["kind"] == "chart":
        return [
            ("orientation", f"Clarify the basic terrain one has to cross to understand {subject}."),
            ("threads", f"Identify the main alignments, commitments, and recurring themes associated with {subject}."),
            ("pressures", f"Highlight the strongest misalignments, criticisms, or points of tension surrounding {subject}."),
            ("discussion", f"Show what later readers should keep debating if they want the chart to remain philosophically alive."),
        ]
    if page["kind"] == "danger":
        return [
            ("orientation", f"Why does {subject} keep attracting human beings, even when it distorts careful inquiry?"),
            ("threads", f"How does {subject} typically operate once it settles into a community or worldview?"),
            ("pressures", f"What are the most serious intellectual and moral costs of normalizing {subject}?"),
            ("discussion", f"What disciplines or counter-habits best protect against {subject}?"),
        ]
    if page["kind"] == "cluster":
        return [
            ("orientation", f"What holds the {subject} cluster together as a recognizable branch or school?"),
            ("threads", f"Which sub-branches, figures, or internal divisions matter most inside {subject}?"),
            ("pressures", f"Where do the strongest tensions or disagreements appear inside {subject}?"),
            ("discussion", f"How should a reader begin moving through {subject} without losing the shape of the whole?"),
        ]
    prompts = source_prompts[:4]
    fallback = [
        f"What is most basically at stake in {subject}?",
        f"What distinctions or internal divisions matter most for understanding {subject} well?",
        f"Where is {subject} most often misunderstood, overstated, or misused?",
        f"What further questions naturally branch outward once {subject} is clarified?",
    ]
    chosen = dedupe(prompts + fallback)[:4]
    anchors = ["orientation", "threads", "pressures", "discussion"]
    return list(zip(anchors, chosen))


def render_paragraphs(parts: Iterable[str]) -> str:
    return "\n".join(f"              <p>{html.escape(part)}</p>" for part in parts if part)


def format_thread_list(items: list[str]) -> str:
    if not items:
        return ""
    lis = "\n".join(f"                <li><strong>{html.escape(item)}:</strong> a live thread that helps organize the branch without exhausting it.</li>" for item in items[:6])
    return f"\n              <ol>\n{lis}\n              </ol>"


def discussion_questions(page: dict, thread_like: list[str]) -> list[str]:
    topic = topic_label(page["title"])
    profile = branch_profile(page["section_id"])
    thread_like = usable_thread_items(thread_like)
    questions = [
        f"Which distinction inside {topic} is easiest to miss when the topic is explained too quickly?",
        f"What is the strongest charitable reading of this topic, and what is the strongest criticism?",
        f"How does this page connect to {profile['lens']}?",
        f"What kind of evidence, argument, or lived pressure should most influence our judgment about {topic}?",
    ]
    if thread_like:
        questions.append(f"Which of these threads matters most right now: {', '.join(thread_like[:3])}?")
    return questions[:5]


def serial_join(items: list[str]) -> str:
    cleaned = [clean_text(item) for item in items if clean_text(item)]
    if not cleaned:
        return ""
    if len(cleaned) == 1:
        return cleaned[0]
    if len(cleaned) == 2:
        return f"{cleaned[0]} and {cleaned[1]}"
    return f"{', '.join(cleaned[:-1])}, and {cleaned[-1]}"


def source_detail_labels(detail: dict | None) -> list[str]:
    if not detail:
        return []
    labels: list[str] = []
    for child in detail.get("children", []):
        labels.append(strip_number_prefix(child.get("title", "")))
    for item in detail.get("items", []):
        label, body = split_label(item)
        if label and body:
            labels.append(label)
    return usable_thread_items(dedupe(labels))[:5]


def prompt_key_phrase(prompt: str, fallback: str) -> str:
    cleaned = clean_text(prompt)
    lowered = cleaned.lower()
    key_phrases = [
        "inductive substrate",
        "sub-absolute confidence",
        "inductive grounding",
        "moral realism",
        "moral non-realism",
        "logical fallacies",
        "training data bias",
        "self-evidence",
        "circularity",
        "human rights",
        "free will",
        "consciousness",
        "truth alignment",
    ]
    for phrase in key_phrases:
        if phrase in lowered:
            return phrase[0].upper() + phrase[1:]

    quoted = re.findall(r"[“\"]([^”\"]{8,90})[”\"]", cleaned)
    if quoted:
        return quoted[0].strip()

    chunks = re.split(r"[.?;:—–-]", cleaned)
    chunks = [chunk.strip() for chunk in chunks if len(chunk.strip()) >= 24]
    if chunks:
        best = max(chunks[:4], key=len)
        if best.count("(") > best.count(")"):
            best = best.split("(", 1)[0].strip()
        return compact_text(best, 90).rstrip(".")
    return fallback


def source_prompt_heading(prompt: str, topic: str, detail: dict | None) -> str:
    labels = source_detail_labels(detail)
    if labels:
        center = labels[0].strip(" .:")
        return f"{center} gives the response its center of gravity."

    key = prompt_key_phrase(prompt, topic)
    if key and key.lower() != topic.lower():
        return f"{key[0].upper() + key[1:]} is the pressure point."
    return prompt_heading(prompt, topic)


def first_source_claim(detail: dict | None) -> str:
    if not detail:
        return ""
    candidates: list[str] = []
    candidates.extend(detail.get("paragraphs", []))
    candidates.extend(detail.get("items", []))
    for child in detail.get("children", []):
        candidates.extend(child.get("paragraphs", []))
        candidates.extend(child.get("items", []))
    for candidate in candidates:
        claim = rewrite_source_sentence(candidate)
        if claim:
            return claim
    return ""


def prompt_focus(prompt: str) -> str:
    lowered = prompt.lower()
    if "dialogue" in lowered:
        return "dialogue"
    if "general description" in lowered or "description of" in lowered:
        return "description"
    if "example" in lowered or "anecdote" in lowered or "case" in lowered:
        return "examples"
    if (
        "list" in lowered
        or "identify" in lowered
        or "primary areas" in lowered
        or "contributions" in lowered
        or "percentage" in lowered
        or "rough estimates" in lowered
        or "for each" in lowered
    ):
        return "mapping"
    if "essay" in lowered or "comment" in lowered or "weigh" in lowered:
        return "argument"
    if lowered.startswith(("what is", "what are")):
        return "definition"
    return "inquiry"


def prompt_heading(prompt: str, topic: str) -> str:
    focus = prompt_focus(prompt)
    if focus == "dialogue":
        return f"A dialogue makes {topic} answerable to another mind."
    if focus == "description":
        return f"A useful description should reveal the working center of {topic}."
    if focus == "examples":
        return f"Examples make {topic} visible in practice."
    if focus == "mapping":
        return f"The map of {topic} matters only if it reveals the structure."
    if focus == "argument":
        return f"The argument about {topic} has to expose its pressure points."
    if focus == "definition":
        return f"A definition of {topic} has to do real work."
    return f"The prompt turns {topic} into a question that can be tested."


def prompt_response_paragraphs(page: dict, prompt: str, index: int, detail: dict | None = None) -> list[str]:
    topic = topic_label(page["title"])
    profile = branch_profile(page["section_id"])
    focus = prompt_focus(prompt)
    labels = source_detail_labels(detail)
    claim = first_source_claim(detail)

    if detail and (labels or claim):
        paragraphs = []
        if labels:
            paragraphs.append(
                f"This response is organized around {serial_join(labels[:3])}. "
                f"Those are the actual steps by which the prompt turns {topic} from a title into a testable philosophical problem."
            )
        else:
            key = prompt_key_phrase(prompt, topic)
            paragraphs.append(
                f"This response centers on {key}, treating it as the point where {topic} needs careful reconstruction rather than quick agreement."
            )

        if claim:
            paragraphs.append(f"The reconstructed answer’s center of gravity is this: {claim}")

        if len(labels) >= 2:
            paragraphs.append(
                f"The important discipline is to keep {labels[0]} distinct from {labels[1]}. "
                f"When those layers are collapsed, the discussion becomes easier to summarize but less honest about the real pressure in the prompt."
            )
        else:
            paragraphs.append(
                f"The point is not to close the issue by slogan. It is to preserve the branch-level pressure: {profile['pressure']}"
            )
        return paragraphs[:3]

    key = prompt_key_phrase(prompt, topic)
    first = (
        f"This response treats {key} as the hinge of {topic}, keeping the question inside the branch discipline of {profile['lens']}. "
        f"{profile['stakes']}"
    )

    if focus == "dialogue":
        second = (
            f"The dialogue form should not be ornamental here. It lets a position be interrupted, clarified, "
            f"and pressed by a live interlocutor, which is often where the real philosophical commitments appear."
        )
    elif focus == "description":
        second = (
            f"A description should give the reader a usable center of gravity: the main claim, the habits it trains, "
            f"and the pressure it places on neighboring views."
        )
    elif focus == "examples":
        second = (
            f"The examples have to carry argumentative weight: they should show how the concept changes judgment, "
            f"where uncertainty remains, and what a reader would handle differently afterward."
        )
    elif focus == "mapping":
        second = (
            f"A list is useful only when it shows relations: what is central, what is peripheral, what depends on "
            f"what, and where neighboring ideas start to compete."
        )
    elif focus == "argument":
        second = (
            f"The essay answer should keep the strongest version of the view in play while also naming the place "
            f"where it becomes vulnerable, overstated, or incomplete."
        )
    elif focus == "definition":
        second = (
            f"The definition should separate ordinary usage from philosophical usage, then show why the distinction "
            f"matters for reasoning beyond this single page."
        )
    else:
        second = (
            f"The answer should discipline the question without pretending that the live difficulty has disappeared. "
            f"{profile['pressure']}"
        )

    return [first, second]


def usable_thread_items(items: Iterable[str]) -> list[str]:
    result = []
    for item in items:
        lowered = clean_text(item).lower()
        if not item or looks_like_prompt(item) or is_low_value_prompt(item):
            continue
        if lowered in {"conclusion", "questions", "introduction"}:
            continue
        if lowered.startswith(("conclusion", "questions")):
            continue
        result.append(item)
    return result


def source_detail_list_items(detail: dict | None, page: dict) -> list[str]:
    if not detail:
        return []

    items: list[str] = []
    children = detail.get("children", [])
    for child in children:
        label = strip_number_prefix(child.get("title", "")).strip(" .:")
        if not label:
            continue
        if len(children) == 1 and "example" in label.lower() and child.get("paragraphs"):
            for paragraph in child["paragraphs"][:6]:
                item_label, item_body = split_label(paragraph)
                if item_label and item_body:
                    items.append(f"{item_label}: {rewrite_source_sentence(item_body)}")
                else:
                    items.append(rewrite_source_sentence(paragraph))
            continue
        body_source = ""
        if child.get("paragraphs"):
            body_source = child["paragraphs"][0]
        elif child.get("items"):
            body_source = child["items"][0]
        if body_source:
            items.append(f"{label}: {rewrite_source_sentence(body_source)}")
        else:
            items.append(f"{label}: This is one of the structural moves the prompt asks the reader to keep distinct.")

    for raw_item in detail.get("items", []):
        label, body = split_label(raw_item)
        if label.lower() in {"pros", "cons"} and len(items) >= 3:
            continue
        if label and body:
            items.append(f"{label}: {rewrite_source_sentence(body)}")
        else:
            items.append(rewrite_source_sentence(raw_item))

    return dedupe([item for item in items if item])[:6]


def section_list_items(page: dict, index: int, prompt: str, detail: dict | None = None) -> list[str]:
    sourced_items = source_detail_list_items(detail, page)
    if sourced_items:
        return sourced_items

    threads = usable_thread_items(page.get("thread_like", []))
    focus = prompt_focus(prompt)
    child_titles = [child["title"] for child in page.get("children", [])]
    topic_items = TOPIC_ITEMS.get(page["title"], [])

    if focus in {"description", "dialogue"} and topic_items:
        return topic_items[:4]

    if focus == "examples":
        examples = [
            item
            for item in threads
            if "–" in item or " - " in item or re.search(r"\b(Case|Scenario|Einstein|Popper|Curie|Darwin|Hume|Kant|Aquinas)\b", item)
        ]
        if examples:
            return examples[:4]

    if focus == "mapping":
        if "contribution" in prompt.lower() and topic_items:
            return topic_items[:4]
        if child_titles and "percentage" not in prompt.lower() and "rough estimates" not in prompt.lower():
            return child_titles[:4]
        mapped = [
            item
            for item in threads
            if not item.lower().startswith(("conclusion", "introduction"))
        ]
        if mapped:
            return mapped[:4]

    start = max(0, (index - 1) * 3)
    items = threads[start : start + 4]
    if items:
        return items
    return branch_profile(page["section_id"])["items"]


def source_prompt_sections(page: dict, prompts: list[str]) -> list[dict]:
    sections = []
    source_details = page.get("source_prompt_details", [])
    for index, prompt in enumerate(prompts, start=1):
        detail = source_details[index - 1] if index - 1 < len(source_details) else None
        sections.append(
            {
                "id": f"prompt-{index}",
                "eyebrow": "Reconstructed Response",
                "heading": source_prompt_heading(prompt, topic_label(page["title"]), detail),
                "paragraphs": prompt_response_paragraphs(page, prompt, index, detail),
                "list_items": section_list_items(page, index, prompt, detail),
            }
        )

    profile = branch_profile(page["section_id"])
    topic_items = TOPIC_ITEMS.get(page["title"], [])
    synthesis_paragraphs = [
        profile["route"],
        profile["pressure"],
    ]
    if topic_items:
        synthesis_paragraphs.append(
            f"For this topic, the durable pressure points include {', '.join(topic_items[:4])}."
        )
    synthesis_paragraphs.append(
        f"Read this page as part of the wider {SECTION_META[page['section_id']]['name']} branch: the prompts point inward to the topic, but they also point outward to neighboring questions that keep the topic honest."
    )

    sections.append(
        {
            "id": "synthesis",
            "eyebrow": "Synthesis",
            "heading": f"The through-line is what this topic asks the reader to notice.",
            "paragraphs": synthesis_paragraphs,
            "question_items": discussion_questions(page, page.get("thread_like", [])),
        }
    )
    return sections


def compose_sections(page: dict) -> list[dict]:
    section_meta = SECTION_META[page["section_id"]]
    topic = topic_label(page["title"])
    profile = branch_profile(page["section_id"])
    threads = page.get("thread_like", [])
    child_titles = [child["title"] for child in page.get("children", [])]
    sibling_titles = page.get("sibling_titles", [])
    child_text = ", ".join(child_titles[:5])
    sibling_text = ", ".join(sibling_titles[:4])

    prompts = curated_source_prompts(page)
    if prompts and page["kind"] not in {"dialogue", "chart"}:
        return source_prompt_sections(page, prompts)

    orientation = [
        f"This reconstruction treats {topic} through the central lens of {section_meta['name'].lower()}: {profile['lens']}.",
        profile["stakes"],
    ]
    threads_paras = [
        f"The strongest way into {topic} is to notice which distinctions keep doing work after the first definition is complete. Those distinctions are the difference between a topic that merely sounds important and one that can discipline judgment.",
    ]
    pressures = [
        profile["pressure"],
        f"A better reconstruction lets {topic} remain difficult where the difficulty is real, while still separating genuine uncertainty from verbal fog, rhetorical comfort, or inherited allegiance.",
    ]
    discussion = [
        profile["route"],
    ]

    if page["kind"] == "dialogue":
        philosopher = topic
        return [
            {
                "id": "voice-fragment",
                "eyebrow": "Voice and Method",
                "heading": f"{philosopher} should sound recognizably like {philosopher}.",
                "paragraphs": [
                    f"This page preserves the philosopher’s voice not by copying the original post line for line, but by keeping the pressure of the original encounter: a voice addressing a reader, making distinctions, resisting shortcuts, and exposing what the view demands.",
                    f"In dialogue pages, tone matters because the thinker’s method is part of the philosophy. A philosopher who teaches by aphorism, disputation, precision, or provocation should not be rebuilt as though every style were interchangeable.",
                ],
            },
            {
                "id": "beginner-dialogue",
                "eyebrow": "For the Beginner",
                "heading": f"The first exchange with {philosopher} should open the door without falsifying the difficulty.",
                "paragraphs": [
                    f"A beginner needs a version of {philosopher} that is lucid without being diluted. The reconstruction therefore starts from the most accessible entry point: the claim that first lets a new reader feel the shape of the system or temperament without needing the whole history of the tradition in advance.",
                    f"The goal is not to trivialize the philosopher. It is to offer the first stable foothold from which the deeper commitments can begin to make sense.",
                ],
            },
            {
                "id": "deeper-dialogue",
                "eyebrow": "For the Fellow Philosopher",
                "heading": f"The deeper exchange with {philosopher} has to reach the structural commitments of the view.",
                "paragraphs": [
                    f"Once the beginner’s footing is secure, the dialogue can become more exacting. This is the point at which definitions, background metaphysics, or methodological commitments start to matter, and where friendly disagreement becomes philosophically productive rather than merely adversarial.",
                    f"The reconstruction keeps that higher register in view so the philosopher is not reduced to a handful of memorable slogans.",
                ],
            },
            {
                "id": "critical-dialogue",
                "eyebrow": "For the Critic",
                "heading": f"The critic matters because {philosopher} becomes clearer under pressure.",
                "paragraphs": [
                    f"The strongest pages of this kind do not protect the philosopher from challenge. They force the view to answer the most intelligent resistance, including places where later readers may reject the framework entirely.",
                    f"That is especially important where the topic touches moral non-realism, theology, authority, or any other fault line where contemporary readers are likely to feel real friction.",
                ],
            },
            {
                "id": "five-notions",
                "eyebrow": "Enduring Notions",
                "heading": f"{philosopher} survives through a cluster of durable moves rather than through total agreement with the system.",
                "paragraphs": [
                    f"What lasts is usually not every conclusion, but a set of distinctions, questions, or argumentative habits that later thinkers continue to use even when they reject the rest. Reconstructing that residue is one of the cleanest ways to show why the philosopher still matters.",
                ],
                "list_items": threads[:5] or [f"Key distinctions associated with {philosopher}", "A durable argumentative method", "A recurring moral or metaphysical pressure point", "A style of criticism that outlived its original context", "A later legacy worth tracing"],
            },
        ]

    if page["kind"] == "chart":
        return [
            {
                "id": "orientation",
                "eyebrow": "Terrain",
                "heading": f"{topic} is best understood as a landscape rather than a slogan.",
                "paragraphs": orientation,
            },
            {
                "id": "threads",
                "eyebrow": "Main Alignments",
                "heading": f"The chart matters because it keeps the major commitments in one field of view.",
                "paragraphs": threads_paras,
                "list_items": threads[:6] or [f"Central commitments associated with {topic}", "Nearby allied positions", "Methods that define the approach", "Claims that make the view distinctive"],
            },
            {
                "id": "pressures",
                "eyebrow": "Misalignments",
                "heading": f"A good chart also marks the places where {topic} comes under pressure.",
                "paragraphs": pressures,
            },
            {
                "id": "discussion",
                "eyebrow": "Carrying It Forward",
                "heading": f"The point of charting {topic} is to improve orientation, not to end debate.",
                "paragraphs": discussion,
            },
        ]

    if page["kind"] == "cluster":
        return [
            {
                "id": "orientation",
                "eyebrow": "Cluster Logic",
                "heading": f"{topic} gathers a set of questions that should be read together.",
                "paragraphs": [
                    f"This cluster belongs in {section_meta['name'].lower()} because it repeatedly returns to {profile['lens']}.",
                    profile["stakes"],
                ],
            },
            {
                "id": "threads",
                "eyebrow": "Sub-Branches",
                "heading": f"The internal structure of {topic} is part of the argument.",
                "paragraphs": [
                    f"This page is a hinge rather than a stopping point. Its nested paths let the reader move from the broad concern to the specific cases where the concern becomes visible.",
                    f"Inside this branch, the most immediate next paths include {child_text or 'several more focused threads that deserve their own pages'}.",
                ],
                "list_items": child_titles[:6] or threads[:6],
            },
            {
                "id": "pressures",
                "eyebrow": "Internal Tensions",
                "heading": f"{topic} becomes more useful when its internal tensions stay visible.",
                "paragraphs": [
                    profile["pressure"],
                    f"The point of preserving the cluster is not to make it look settled. It is to keep the reader oriented while the sub-pages do their sharper work.",
                ],
            },
            {
                "id": "discussion",
                "eyebrow": "How to Begin",
                "heading": f"{topic} becomes manageable when the reader knows what to test first.",
                "paragraphs": [
                    profile["route"],
                ],
            },
        ]

    return [
        {
            "id": "orientation",
            "eyebrow": "Orientation",
            "heading": f"{topic} becomes clearer when the branch question is kept in view.",
            "paragraphs": orientation,
        },
        {
            "id": "threads",
            "eyebrow": "Key Threads",
            "heading": f"The strongest way into {topic} is through its recurring distinctions and lines of inquiry.",
            "paragraphs": threads_paras,
            "list_items": threads[:6],
        },
        {
            "id": "pressures",
            "eyebrow": "Pressures and Misuses",
            "heading": f"{topic} is most often distorted where the branch discipline is relaxed.",
            "paragraphs": pressures,
        },
        {
            "id": "discussion",
            "eyebrow": "Discussion Routes",
            "heading": f"{topic} opens more questions than any single page can close.",
            "paragraphs": discussion,
            "question_items": discussion_questions(page, threads),
        },
    ]


def render_list_section(items: list[str], item_tag: str = "li") -> str:
    if not items:
        return ""
    rendered_items = []
    for item in items:
        label, body = split_label(item)
        if label and body and item_tag == "li":
            rendered_items.append(
                f"                <li><strong>{html.escape(label)}:</strong> {html.escape(body)}</li>"
            )
        else:
            rendered_items.append(f"                <{item_tag}>{html.escape(item)}</{item_tag}>")
    inner = "\n".join(rendered_items)
    return f"\n              <ol>\n{inner}\n              </ol>"


def render_article_page(page: dict) -> str:
    section_meta = SECTION_META[page["section_id"]]
    prompts = prompt_pack(page, section_meta)
    sections = compose_sections(page)
    standfirst = generic_standfirst(page, section_meta)
    page_path = page["built_path"]
    depth = len(Path(page_path.strip("/")).parts)
    prefix = "../" * depth
    breadcrumbs = [
        f'<a href="{prefix}index.html">Home</a>',
        f'<a href="{prefix}index.html#section-{page["section_id"]}">{html.escape(section_meta["name"])}</a>',
        f"<span>{html.escape(page['title'])}</span>",
    ]
    prompt_html = "\n".join(
        f'              <li><a href="#{anchor}">{html.escape(text)}</a></li>' for anchor, text in prompts
    )

    body_parts = []
    for section in sections:
        block = [
            f'            <section class="article-section" id="{section["id"]}">',
            f'              <p class="eyebrow">{html.escape(section["eyebrow"])}</p>',
            f'              <h2>{html.escape(section["heading"])}</h2>',
            render_paragraphs(section.get("paragraphs", [])),
        ]
        if section.get("list_items"):
            block.append(render_list_section(section["list_items"]))
        if section.get("question_items"):
            block.append(render_list_section(section["question_items"]))
        block.append("            </section>")
        body_parts.append("\n".join(part for part in block if part))

    tags = tag_candidates(page, section_meta)
    tag_html = "\n".join(f'                <span class="tag-chip">{html.escape(tag)}</span>' for tag in tags)
    child_titles = [child["title"] for child in page.get("children", [])][:6]
    sibling_titles = [title for title in page.get("sibling_titles", []) if title != page["title"]][:4]
    future_parts = []
    if child_titles:
        future_parts.append(f"This branch opens directly into <strong>{'</strong>, <strong>'.join(html.escape(title) for title in child_titles)}</strong>.")
    if sibling_titles:
        future_parts.append(f"Nearby pages in the same branch include <strong>{'</strong>, <strong>'.join(html.escape(title) for title in sibling_titles)}</strong>.")
    if not future_parts:
        future_parts.append(f"This page belongs inside the wider <strong>{html.escape(section_meta['name'])}</strong> branch and is best read in conversation with its neighboring topics.")
    future_paragraph = " ".join(future_parts)
    footer_note = f"This reconstructed page keeps the archive voice consistent while leaving room for later deepening where the branch deserves it most."

    return textwrap.dedent(
        f"""\
        {AUTO_MARKER}
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>{html.escape(page["title"])} | Byteseismic Reconstruction</title>
            <meta
              name="description"
              content="{html.escape(standfirst)}"
            />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link
              href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=Newsreader:opsz,wght@6..72,500;6..72,700&family=Spline+Sans:wght@400;500;600;700&display=swap"
              rel="stylesheet"
            />
            <link rel="stylesheet" href="{prefix}assets/css/styles.css" />
            <script defer src="{prefix}assets/js/site-data.js"></script>
            <script defer src="{prefix}assets/js/site.js"></script>
          </head>
          <body
            data-page-type="article"
            data-current-section="{page["section_id"]}"
            data-current-page="{page["built_path"]}"
          >
            <div class="page-shell">
              <header class="hero hero--article">
                <img
                  class="hero__image"
                  src="{prefix}assets/images/byteseismic-large-header-x.5-b-8000-x-800-px.png"
                  alt="Byteseismic banner"
                />
                <div class="hero__content">
                  <div class="breadcrumbs">
                    {'<span>/</span>'.join(breadcrumbs)}
                  </div>
                  <p class="hero__kicker">{html.escape(section_meta["name"])}</p>
                  <h1>{html.escape(page["title"])}</h1>
                  <p class="article-standfirst">
                    {html.escape(standfirst)}
                  </p>
                </div>
              </header>

              <div class="article-layout article-layout--single">
                <main class="article-stack">
                  <section class="prompt-ledger">
                    <p class="eyebrow">Prompts</p>
                    <h2>Prompts</h2>
                    <ol>
        {prompt_html}
                    </ol>
                  </section>

                  <div class="article-body">
        {'\n\n'.join(body_parts)}

                    <section class="article-section" id="future-branches">
                      <p class="eyebrow">Future Branches</p>
                      <h2>Where this page naturally expands</h2>
                      <div class="tag-row">
        {tag_html}
                      </div>
                      <p>
                        {future_paragraph}
                      </p>
                    </section>
                  </div>

                  <section class="article-outline-slot" data-article-outline></section>

                  <section class="process-note">
                    <p>
                      This post is a final compilation of ideas and concepts distilled from interactions
                      between the curator’s prompts and multiple AI interlocutors. The prompts are kept
                      in spirit, the prose is newly written, and irreducible structural features are
                      preserved where they carry genuine philosophical value.
                    </p>
                  </section>
                </main>
              </div>

              <footer class="site-footer">
                <p>
                  {footer_note}
                </p>
              </footer>
            </div>
          </body>
        </html>
        """
    )


def render_menu_structure_page() -> str:
    return textwrap.dedent(
        f"""\
        {AUTO_MARKER}
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Site Map | Byteseismic Reconstruction</title>
            <meta
              name="description"
              content="A nested map of the reconstructed Byteseismic archive, preserving the visible branch structure while linking into the rebuilt pages."
            />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link
              href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=Newsreader:opsz,wght@6..72,500;6..72,700&family=Spline+Sans:wght@400;500;600;700&display=swap"
              rel="stylesheet"
            />
            <link rel="stylesheet" href="../assets/css/styles.css" />
            <script defer src="../assets/js/site-data.js"></script>
            <script defer src="../assets/js/site.js"></script>
          </head>
          <body data-page-type="archive">
            <div class="page-shell">
              <header class="hero">
                <img
                  class="hero__image"
                  src="../assets/images/byteseismic-large-header-x.5-b-8000-x-800-px.png"
                  alt="Byteseismic banner"
                />
                <div class="hero__content">
                  <div class="breadcrumbs">
                    <a href="../index.html">Home</a>
                    <span>/</span>
                    <span>Site Map</span>
                  </div>
                  <p class="hero__kicker">Archive Map</p>
                  <h1>Site Map</h1>
                  <p class="hero__lede">
                    A nested view of the reconstructed archive, preserving the visible old hierarchy
                    while pointing each branch toward its rebuilt pages.
                  </p>
                </div>
              </header>

              <main class="content">
                <section class="content-card" data-site-nav></section>
                <section class="content-card">
                  <div class="structure-grid" data-section-grid></div>
                </section>
              </main>
            </div>
          </body>
        </html>
        """
    )


def render_expanded_archive_page(posts_by_year: dict[int, list[dict]], section_counts: dict[str, int]) -> str:
    year_blocks = []
    for year in sorted(posts_by_year.keys(), reverse=True):
        items = "\n".join(
            f'              <li><a href="..{post["built_path"]}">{html.escape(post["title"])}</a><span>{html.escape(SECTION_META[post["section_id"]]["name"])}</span></li>'
            for post in sorted(posts_by_year[year], key=lambda item: item["title"].lower())
        )
        year_blocks.append(
            f"""\
            <section class="article-section">
              <p class="eyebrow">Archive Year</p>
              <h2>{year}</h2>
              <ul class="archive-year-list">
{items}
              </ul>
            </section>"""
        )

    count_items = "\n".join(
        f'                <li><strong>{html.escape(SECTION_META[section_id]["name"])}:</strong> {count}</li>'
        for section_id, count in sorted(section_counts.items(), key=lambda item: SECTION_META[item[0]]["name"])
    )

    return textwrap.dedent(
        f"""\
        {AUTO_MARKER}
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Recent Posts — Expanded Version | Byteseismic Reconstruction</title>
            <meta
              name="description"
              content="An expanded archive page listing the rebuilt Byteseismic posts across years and sections."
            />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link
              href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=Newsreader:opsz,wght@6..72,500;6..72,700&family=Spline+Sans:wght@400;500;600;700&display=swap"
              rel="stylesheet"
            />
            <link rel="stylesheet" href="../assets/css/styles.css" />
          </head>
          <body>
            <div class="page-shell">
              <header class="hero hero--article">
                <img
                  class="hero__image"
                  src="../assets/images/byteseismic-large-header-x.5-b-8000-x-800-px.png"
                  alt="Byteseismic banner"
                />
                <div class="hero__content">
                  <div class="breadcrumbs">
                    <a href="../index.html">Home</a>
                    <span>/</span>
                    <span>Recent Posts — Expanded Version</span>
                  </div>
                  <p class="hero__kicker">Expanded Archive</p>
                  <h1>Recent Posts — Expanded Version</h1>
                  <p class="article-standfirst">
                    A wide-angle archive page reflecting the broader public post history while the
                    curated branch hierarchy remains the main navigational spine.
                  </p>
                </div>
              </header>

              <div class="article-layout article-layout--single">
                <main class="article-stack">
                  <section class="content-card">
                    <p class="eyebrow">Archive Scope</p>
                    <h2>Section distribution</h2>
                    <ul>
{count_items}
                    </ul>
                  </section>

                  <div class="article-body">
        {'\n\n'.join(year_blocks)}
                  </div>
                </main>
              </div>
            </div>
          </body>
        </html>
        """
    )


def render_podcast_page() -> str:
    return textwrap.dedent(
        f"""\
        {AUTO_MARKER}
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Byteseismic Podcasts | Byteseismic Reconstruction</title>
            <meta
              name="description"
              content="A holding page for the audio branch of the reconstructed Byteseismic archive."
            />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link
              href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=Newsreader:opsz,wght@6..72,500;6..72,700&family=Spline+Sans:wght@400;500;600;700&display=swap"
              rel="stylesheet"
            />
            <link rel="stylesheet" href="../assets/css/styles.css" />
          </head>
          <body>
            <div class="page-shell">
              <header class="hero hero--article">
                <img
                  class="hero__image"
                  src="../assets/images/byteseismic-large-header-x.5-b-8000-x-800-px.png"
                  alt="Byteseismic banner"
                />
                <div class="hero__content">
                  <div class="breadcrumbs">
                    <a href="../index.html">Home</a>
                    <span>/</span>
                    <span>Byteseismic Podcasts</span>
                  </div>
                  <p class="hero__kicker">Podcast</p>
                  <h1>Byteseismic Podcasts</h1>
                  <p class="article-standfirst">
                    A branch page reserved for audio adaptations, curated episode groupings, and future spoken companions to the written archive.
                  </p>
                </div>
              </header>

              <div class="article-layout article-layout--single">
                <main class="article-stack">
                  <section class="content-card">
                    <p class="eyebrow">Audio Branch</p>
                    <h2>This branch is being rebuilt as a companion to the written archive.</h2>
                    <p>
                      The new site is prioritizing the post archive first, then the spoken adaptations.
                      As the audio branch grows, it can gather curated episode paths, philosopher mini-series,
                      and companion recordings for major conceptual branches.
                    </p>
                  </section>
                </main>
              </div>
            </div>
          </body>
        </html>
        """
    )


def write_if_allowed(target: Path, contents: str) -> bool:
    if target.exists():
        existing = target.read_text()
        if AUTO_MARKER not in existing:
            return False
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(contents)
    return True


def cleanup_auto_generated(valid_targets: set[Path]) -> None:
    for target in ROOT.rglob("index.html"):
        if target in valid_targets:
            continue
        if AUTO_MARKER not in target.read_text():
            continue
        target.unlink()
        parent = target.parent
        while parent != ROOT and not any(parent.iterdir()):
            parent.rmdir()
            parent = parent.parent


def node_to_topic_tree(nodes: list[dict]) -> list[dict]:
    tree = []
    for node in nodes:
        entry = {"title": node["title"]}
        if node.get("built_path"):
            entry["path"] = node["built_path"]
        if node.get("children"):
            entry["children"] = node_to_topic_tree(node["children"])
        tree.append(entry)
    return tree


def flatten_visible_nodes(nodes: list[dict]) -> list[dict]:
    flat = []
    for node in nodes:
        flat.append(node)
        flat.extend(flatten_visible_nodes(node.get("children", [])))
    return flat


def main() -> None:
    home_html = fetch_homepage_html()
    section_nodes = section_nodes_from_home(home_html)
    all_posts = fetch_all_posts()

    visible_lookup: dict[str, dict] = {}
    for section_id, nodes in section_nodes.items():
        visible_lookup.update(hierarchy_lookup(nodes, section_id))

    posts_by_url = {canonical_url(post["URL"]): post for post in all_posts if post.get("URL")}
    generated_pages: list[dict] = []
    page_index: dict[tuple[str, str], dict] = {}

    def register_page(
        title: str,
        section_id: str,
        built_path: str,
        source_url: str = "",
        post: dict | None = None,
        children: list[dict] | None = None,
        sibling_titles: list[str] | None = None,
    ) -> dict:
        key = (section_id, built_path)
        if key in page_index:
            page = page_index[key]
            if children is not None:
                page["children"] = children
            if sibling_titles is not None:
                page["sibling_titles"] = sibling_titles
            return page

        source_prompts, thread_like, _paragraphs = ([], [], [])
        source_prompt_details: list[dict] = []
        if post:
            source_prompts, thread_like, _paragraphs = normalize_heading_list(
                post.get("content", ""),
                clean_text(title),
            )
            source_prompt_details = extract_source_prompt_details(
                post.get("content", ""),
                clean_text(title),
            )
            if source_prompt_details:
                source_prompts = [detail["prompt"] for detail in source_prompt_details]
        page = {
            "title": clean_text(title),
            "section_id": section_id,
            "built_path": built_path,
            "source_url": source_url,
            "kind": infer_kind(title, bool(children)),
            "source_prompts": source_prompts,
            "source_prompt_details": source_prompt_details,
            "thread_like": thread_like,
            "excerpt": strip_html(post.get("excerpt", "") if post else ""),
            "date": post.get("date", "") if post else "",
            "children": children or [],
            "sibling_titles": sibling_titles or [],
        }
        page_index[key] = page
        generated_pages.append(page)
        return page

    def assign_visible_paths(section_id: str, nodes: list[dict], siblings: list[str] | None = None) -> None:
        sibling_titles = siblings or [node["title"] for node in nodes]
        for node in nodes:
            href = node.get("href", "")
            canonical = canonical_url(href) if href and "byteseismic.com" in href else ""
            post = posts_by_url.get(canonical)
            synthetic = not post and (not href or "wordpress.com" in href or "#" in href)
            built_path = build_path_for_node(section_id, node["title"], source_url=href, synthetic=synthetic)
            node["built_path"] = built_path
            if post:
                register_page(
                    title=node["title"],
                    section_id=section_id,
                    built_path=built_path,
                    source_url=canonical,
                    post=post,
                    children=node.get("children", []),
                    sibling_titles=sibling_titles,
                )
            else:
                register_page(
                    title=node["title"],
                    section_id=section_id,
                    built_path=built_path,
                    source_url=canonical or href,
                    children=node.get("children", []),
                    sibling_titles=sibling_titles,
                )
            if node.get("children"):
                assign_visible_paths(section_id, node["children"], [child["title"] for child in node["children"]])

    for section_id, nodes in section_nodes.items():
        assign_visible_paths(section_id, nodes)

    visible_urls = {canonical_url(post["URL"]) for post in all_posts if canonical_url(post["URL"]) in visible_lookup}

    for post in all_posts:
        canonical = canonical_url(post["URL"])
        if canonical in visible_urls:
            continue
        override = FEATURED_PATHS_BY_TITLE.get(clean_text(post["title"]).lower())
        if override:
            section_id, built_path = override
        else:
            section_id = classify_section(post)
            built_path = f"/{section_id}/{slugify(post['slug'])}/"
        register_page(
            title=clean_text(post["title"]),
            section_id=section_id,
            built_path=built_path,
            source_url=canonical,
            post=post,
        )

    generated_pages.sort(key=lambda item: (item["section_id"], item["title"].lower()))

    valid_targets: set[Path] = set()
    for page in generated_pages:
        if page["built_path"] in GROUP_PAGE_TITLES.values():
            continue
        target = ROOT / page["built_path"].strip("/") / "index.html"
        valid_targets.add(target)
        write_if_allowed(target, render_article_page(page))

    menu_target = ROOT / "menu-structure" / "index.html"
    podcast_target = ROOT / "byteseismic-podcasts" / "index.html"
    archive_target = ROOT / "recent-posts-expanded-version" / "index.html"
    valid_targets.update({menu_target, podcast_target, archive_target})

    write_if_allowed(menu_target, render_menu_structure_page())
    write_if_allowed(podcast_target, render_podcast_page())

    posts_by_year: dict[int, list[dict]] = defaultdict(list)
    section_counts: dict[str, int] = defaultdict(int)
    for page in generated_pages:
        if not page["date"]:
            continue
        year = int(page["date"][:4])
        posts_by_year[year].append(page)
        section_counts[page["section_id"]] += 1

    write_if_allowed(archive_target, render_expanded_archive_page(posts_by_year, section_counts))

    def choose_featured_pages() -> list[dict]:
        chosen = []
        seen_sections = set()
        path_lookup = {page["built_path"]: page for page in generated_pages}
        for spec in FEATURED_PAGE_SPECS:
            page = path_lookup.get(spec["path"])
            section_meta = SECTION_META[spec["section_id"]]
            if page is None:
                pseudo_page = {
                    "title": spec["title"],
                    "section_id": spec["section_id"],
                    "kind": infer_kind(spec["title"], False),
                }
                chosen.append(
                    {
                        "title": spec["title"],
                        "section": section_meta["name"],
                        "path": spec["path"],
                        "summary": feature_summary(pseudo_page, section_meta),
                        "tags": tag_candidates(pseudo_page, section_meta),
                    }
                )
                seen_sections.add(spec["section_id"])
                continue

            chosen.append(
                {
                    "title": page["title"],
                    "section": section_meta["name"],
                    "path": spec["path"],
                    "summary": feature_summary(page, section_meta),
                    "tags": tag_candidates(page, section_meta),
                }
            )
            seen_sections.add(spec["section_id"])
        for section_id in SECTION_IDS:
            if section_id in seen_sections:
                continue
            section_pages = [page for page in generated_pages if page["section_id"] == section_id]
            if not section_pages:
                continue
            page = section_pages[0]
            section_meta = SECTION_META[section_id]
            chosen.append(
                {
                    "title": page["title"],
                    "section": section_meta["name"],
                    "path": page["built_path"],
                    "summary": feature_summary(page, section_meta),
                    "tags": tag_candidates(page, section_meta),
                }
            )
        return chosen

    featured_pages = choose_featured_pages()

    topic_paths = {
        "Site Map": "/menu-structure/",
        "Recent Posts — Expanded Version": "/recent-posts-expanded-version/",
    }
    for spec in FEATURED_PAGE_SPECS:
        topic_paths[spec["title"]] = spec["path"]
    sections_data = []
    for section_id in SECTION_IDS:
        meta = SECTION_META[section_id]
        nodes = section_nodes.get(section_id, [])
        topic_tree = node_to_topic_tree(nodes)
        flat_nodes = flatten_visible_nodes(nodes)
        for node in flat_nodes:
            if node.get("built_path"):
                topic_paths[node["title"]] = node["built_path"]
        visible_titles = [node["title"] for node in flat_nodes]
        sample_path = meta.get("preferredPath")
        if not sample_path and flat_nodes:
            sample_path = flat_nodes[0].get("built_path")
        sections_data.append(
            {
                "id": section_id,
                "name": meta["name"],
                "summary": meta["summary"],
                "seedTopics": visible_titles[:8],
                "topicCount": len(visible_titles),
                "futureTags": meta["futureTags"],
                "samplePath": sample_path,
                "topicTree": topic_tree,
            }
        )

    data = {
        "siteTitle": "Byteseismic Philosophy",
        "siteTagline": "Final compilations of philosophical ideas distilled from the curator's prompts and multiple AI interlocutors.",
        "featuredPages": featured_pages,
        "topicPaths": topic_paths,
        "sections": sections_data,
    }
    site_data_js = "window.BYTESEISMIC_DATA = " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n"
    (ROOT / "assets" / "js" / "site-data.js").write_text(site_data_js)
    cleanup_auto_generated(valid_targets)

    print(f"Generated or updated {len(generated_pages)} content pages.")
    print(f"Visible hierarchy sections: {len(section_nodes)}")
    print(f"Expanded archive years: {len(posts_by_year)}")


if __name__ == "__main__":
    main()
