#!/usr/bin/env python3
"""Render the reviewed cycle-7 batch from its committed editorial baseline.

Only currentBatch pages can be written. The HTML is intentionally maintained
by editors after this pass: the normal archive builder respects that marker.
Use --check after completion; it does not require the cursor to remain here.
"""
from __future__ import annotations

import argparse
import json
import subprocess
from collections import Counter
from pathlib import Path

from bs4 import BeautifulSoup, Comment

from editorial_batch_100_content import EDITS

ROOT = Path(__file__).resolve().parents[1]
BASE = "d9cfa71b3"
MARKER = " EDITORIALLY MAINTAINED: cycle 7 batch 100; see scripts/editorial_batch_100.py "


def text(node):
    return node.get_text(" ", strip=True)


def baseline(path):
    return subprocess.check_output(["git", "show", f"{BASE}:{path}"], cwd=ROOT, text=True)


def fragment(value):
    return list(BeautifulSoup(value, "html.parser").contents)


def render(original, edits):
    soup = BeautifulSoup(original, "html.parser")
    for comment in soup.find_all(string=lambda n: isinstance(n, Comment)):
        if "AUTO-GENERATED BY scripts/build_archive.py" in comment:
            comment.replace_with(Comment(MARKER))

    # These recurring editorial instructions add no subject-matter content.
    # Restrict cleanup to direct exposition and learning cards, never source
    # prompts, quotations, dialogue turns, or recovered curator exchanges.
    for section in soup.select(".article-section--prompt, #synthesis"):
        for p in list(section.find_all("p", recursive=False)):
            if "article-section__prompt" in p.get("class", []):
                continue
            if text(p).startswith(("The point of mapping ", "Once the boundaries are visible, later disagreements", "The real test is whether Training Data Bias", "That requires separating what the argument has actually established", "The reader should leave with a narrower disagreement")):
                p.decompose()
        for card in section.select("aside.learning-card"):
            for item in list(card.select("li")):
                if text(item).startswith(("Read the map as dependencies, not inventory:", "Use testable promises inside ", "Ask what live problem made Philosopher", "Ask what live problem made Philosophical Gradients", "Look for dependencies: ask which part of Philosophers or Philosophy", "Notice the inheritance trail: later thinkers often keep Philosophers or Philosophy")):
                    item.decompose()
            if not card.select("li"):
                card.decompose()

    for edit in edits:
        section = soup.select_one("#" + edit["anchor"])
        if section is None:
            raise ValueError(f"Missing anchor: {edit['anchor']}")
        heading = section.find("h2", recursive=False)
        if edit.get("heading"):
            heading.string = edit["heading"]
        if edit.get("replace_body"):
            for child in list(section.children):
                if getattr(child, "name", None) and child is not heading and "article-section__meta" not in child.get("class", []) and "article-section__prompt" not in child.get("class", []):
                    child.decompose()
        elif edit.get("replace_intro"):
            for p in list(section.find_all("p", recursive=False)):
                if "article-section__prompt" not in p.get("class", []):
                    p.decompose()
        for replacement in edit.get("replacements", []):
            old, new = replacement
            matches = [n for n in section.find_all(["p", "li"]) if text(n) == old]
            if len(matches) != 1:
                raise ValueError(f"Expected one replacement match: {old[:70]} ({len(matches)})")
            matches[0].clear()
            for node in fragment(new):
                matches[0].append(node)
        if edit.get("html"):
            # Insert directly after the section heading: definitions and worked
            # examples prepare readers for the existing detailed response.
            cursor = heading
            for node in fragment(edit["html"]):
                cursor.insert_after(node)
                cursor = node

    modified = soup.select_one('meta[property="article:modified_time"]')
    if modified:
        modified["content"] = "2026-09-04"
    for data in soup.select('script[type="application/ld+json"]'):
        payload = json.loads(data.string or "{}")
        if isinstance(payload, dict) and payload.get("@type") == "Article":
            payload["dateModified"] = "2026-09-04"
            data.string = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return "\n".join(line.rstrip() for line in str(soup).splitlines()) + "\n"


def check(path, expected=None):
    original = BeautifulSoup(baseline(path), "html.parser")
    result = (ROOT / path).read_text()
    soup = BeautifulSoup(result, "html.parser")
    assert MARKER.strip() in result, path
    if expected is not None:
        assert result == expected, f"Non-reproducible output: {path}"
    for selector in (".article-section__prompt", ".prompt-ledger__text", "#dialectical-turn"):
        assert [text(n) for n in original.select(selector)] == [text(n) for n in soup.select(selector)], (path, selector)
    ids = [n["id"] for n in soup.select("[id]")]
    assert all(count == 1 for count in Counter(ids).values()), f"Duplicate IDs: {path}"
    assert len(original.select(".article-section--prompt")) == len(soup.select(".article-section--prompt")), path
    assert all(s.find("h2") and len(text(s).split()) > 45 for s in soup.select(".article-section--prompt")), path
    assert all(soup.find(id=a["href"][1:]) for a in soup.select('a[href^="#"]') if len(a["href"]) > 1), f"Broken fragment: {path}"
    # Preserve every dialogue except explicitly replaced composite responses.
    replaced = {e["anchor"] for e in EDITS[path] if e.get("replace_body") or e.get("replacements")}
    for section in original.select(".article-section--prompt"):
        if section["id"] not in replaced:
            assert [text(n) for n in section.select(".dialogue-turn")] == [text(n) for n in soup.find(id=section["id"]).select(".dialogue-turn")], path
    return len(soup.select(".article-section--prompt"))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--built-root", type=Path, help="With --check, verify that a full archive build preserved every reviewed file byte-for-byte")
    args = parser.parse_args()
    if args.built_root and not args.check:
        parser.error("--built-root requires --check")
    if not args.check:
        tracker = json.loads((ROOT / "quality/editorial-audit-tracker.json").read_text())
        paths = {p["pagePath"].strip("/") + "/index.html" for p in tracker["currentBatch"]["pages"]}
        assert paths == set(EDITS), "Refusing to write outside the authoritative batch"
    count = 0
    for path, edits in EDITS.items():
        expected = render(baseline(path), edits)
        if not args.check:
            target = ROOT / path
            # Do not overwrite later editorial changes when this is rerun.
            assert target.read_text() in (baseline(path), expected), f"Unexpected edits: {path}"
            target.write_text(expected)
        count += check(path, expected)
        if args.built_root:
            assert (args.built_root / path).read_bytes() == (ROOT / path).read_bytes(), f"Archive build changed reviewed page: {path}"
    print(f"Verified {len(EDITS)} pages, {count} prompt sections; source questions, recovered exchanges, anchors, and reproducibility preserved.")
    if args.built_root:
        print("Full archive build preserved all 50 reviewed files byte-for-byte.")


if __name__ == "__main__":
    main()
