#!/usr/bin/env python3
"""Render and verify the reviewed cycle-7 batch at queue positions 201–250."""
from __future__ import annotations

import argparse
import json
import subprocess
from collections import Counter
from pathlib import Path

from bs4 import BeautifulSoup, Comment

from editorial_batch_200_content import EDITS

ROOT = Path(__file__).resolve().parents[1]
BASE = "HEAD"
MARKER = " EDITORIALLY MAINTAINED: cycle 7 batch 200; see scripts/editorial_batch_200.py "


def text(node):
    return node.get_text(" ", strip=True)


def baseline(path):
    return subprocess.check_output(["git", "show", f"{BASE}:{path}"], cwd=ROOT, text=True)


def render(original, edit):
    soup = BeautifulSoup(original, "html.parser")
    for comment in soup.find_all(string=lambda n: isinstance(n, Comment)):
        if "AUTO-GENERATED BY scripts/build_archive.py" in comment:
            comment.replace_with(Comment(MARKER))
    section = soup.select_one("#" + edit["anchor"])
    if section is None:
        raise ValueError(f"Missing anchor {edit['anchor']}")
    heading = section.find("h2", recursive=False)
    heading.string = edit["heading"]
    addition = soup.new_tag("p")
    addition["class"] = ["editorial-clarification"]
    addition.string = edit["paragraph"]
    prompt = section.select_one(".article-section__prompt")
    if prompt:
        prompt.insert_after(addition)
    else:
        heading.insert_after(addition)
    modified = soup.select_one('meta[property="article:modified_time"]')
    if modified:
        modified["content"] = "2026-09-06"
    for data in soup.select('script[type="application/ld+json"]'):
        payload = json.loads(data.string or "{}")
        if isinstance(payload, dict) and payload.get("@type") == "Article":
            payload["dateModified"] = "2026-09-06"
            data.string = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return "\n".join(line.rstrip() for line in str(soup).splitlines()) + "\n"


def check(path, expected=None):
    source = BeautifulSoup(baseline(path), "html.parser")
    result = (ROOT / path).read_text()
    soup = BeautifulSoup(result, "html.parser")
    assert MARKER.strip() in result, path
    if expected is not None:
        assert result == expected, f"Non-reproducible output: {path}"
    for selector in (".article-section__prompt", ".prompt-ledger__text", "#dialectical-turn"):
        assert [text(n) for n in source.select(selector)] == [text(n) for n in soup.select(selector)], (path, selector)
    assert len(source.select(".article-section--prompt")) == len(soup.select(".article-section--prompt")), path
    assert len(soup.select(".editorial-clarification")) == 1, path
    ids = [n["id"] for n in soup.select("[id]")]
    assert all(n == 1 for n in Counter(ids).values()), f"Duplicate IDs: {path}"
    assert all(soup.find(id=a["href"][1:]) for a in soup.select('a[href^="#"]') if len(a["href"]) > 1), f"Broken fragment: {path}"
    return len(soup.select(".article-section--prompt"))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--built-root", type=Path)
    args = parser.parse_args()
    if args.built_root and not args.check:
        parser.error("--built-root requires --check")
    if not args.check:
        tracker = json.loads((ROOT / "quality/editorial-audit-tracker.json").read_text())
        paths = {p["pagePath"].strip("/") + "/index.html" for p in tracker["currentBatch"]["pages"]}
        assert paths == set(EDITS), "Refusing to write outside the authoritative batch"
    section_count = 0
    for path, edit in EDITS.items():
        expected = render(baseline(path), edit)
        if not args.check:
            (ROOT / path).write_text(expected)
        section_count += check(path, expected)
        if args.built_root:
            assert (args.built_root / path).read_bytes() == (ROOT / path).read_bytes(), f"Archive build changed reviewed page: {path}"
    print(f"Verified {len(EDITS)} pages and {section_count} prompt sections; prompts, curator exchange, IDs, anchors, and deterministic output preserved.")
    if args.built_root:
        print("Full archive build preserved all 50 reviewed files byte-for-byte.")


if __name__ == "__main__":
    main()
