#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path

from bs4 import BeautifulSoup


ROOT = Path(__file__).resolve().parents[1]
TRACKER_PATH = ROOT / "quality" / "editorial-audit-tracker.json"
AUTO_MARKER = "<!-- AUTO-GENERATED BY scripts/build_archive.py -->"


REMOVE_PARAGRAPH_PATTERNS = [
    re.compile(r"^The section works only if .+", re.IGNORECASE),
    re.compile(r"^The question matters because it changes what the reader would now compare.+", re.IGNORECASE),
    re.compile(r"^The pressure point is whether .+", re.IGNORECASE),
    re.compile(r"^At the center is a simpler claim:.+", re.IGNORECASE),
    re.compile(r"^.+ need to stay distinct here, because they answer different questions and carry different explanatory weight\.$", re.IGNORECASE),
    re.compile(r"^Put the issue into a live setting\..+", re.IGNORECASE),
    re.compile(r"^Run one live case through the structure\..+", re.IGNORECASE),
    re.compile(r"^Picture a serious critic who grants the background but resists the move toward .+", re.IGNORECASE),
    re.compile(r"^Read .+ as separate levers in the argument .+", re.IGNORECASE),
    re.compile(r"^The obvious resistance is that real judgment is often fast, social, and pressured\..+", re.IGNORECASE),
    re.compile(r"^A likely objection is that the ordinary way of talking about .+", re.IGNORECASE),
    re.compile(r"^The natural pushback is that ordinary life runs on incomplete evidence\..+", re.IGNORECASE),
    re.compile(r"^The payoff (?:here|of .+) is .+", re.IGNORECASE),
    re.compile(r"^The section should clarify how .+", re.IGNORECASE),
    re.compile(r"^Put the distinction under pressure\..+", re.IGNORECASE),
    re.compile(r"^Keep .+ in the same frame\.", re.IGNORECASE),
    re.compile(r"^Keep .+ distinct from .+\.", re.IGNORECASE),
    re.compile(r"^Keep .+ in view at the same time\.", re.IGNORECASE),
    re.compile(r"^Read the section by contrast:", re.IGNORECASE),
    re.compile(r"^Read the section through ", re.IGNORECASE),
    re.compile(r"^Take one concrete case and run it through ", re.IGNORECASE),
    re.compile(r"^A quick way to test the page ", re.IGNORECASE),
    re.compile(r"^Bring the issue down to street level\.", re.IGNORECASE),
    re.compile(r"^The first move should ", re.IGNORECASE),
    re.compile(r"^This middle step keeps ", re.IGNORECASE),
    re.compile(r"^This middle step prepares ", re.IGNORECASE),
    re.compile(r"^By this point the clearing work should ", re.IGNORECASE),
    re.compile(r"^A fair pushback is that the familiar way of speaking ", re.IGNORECASE),
    re.compile(r"^A fair question is why this map is needed at all\.", re.IGNORECASE),
    re.compile(r"^One honest test after reading is whether ", re.IGNORECASE),
    re.compile(r"^Treat .+ as handles, not slogans\.", re.IGNORECASE),
    re.compile(r"^Do not let the example sit there like a decorative vase\.", re.IGNORECASE),
    re.compile(r"^The human-machine exchange is healthiest ", re.IGNORECASE),
    re.compile(r"^The real test of .+ is whether ", re.IGNORECASE),
    re.compile(r"^.+ should remain tied to a live intellectual practice\.", re.IGNORECASE),
]


def load_batch_paths() -> list[Path]:
    tracker = json.loads(TRACKER_PATH.read_text())
    return [ROOT / page["pagePath"].strip("/") / "index.html" for page in tracker["currentBatch"]["pages"]]


def normalize_heading_text(text: str) -> str:
    text = " ".join(text.split())

    match = re.fullmatch(r"The real issue is what (.+) changes once it becomes precise\.", text)
    if match:
        return f"What changes once we define {match.group(1)} more carefully"

    match = re.fullmatch(r"A concrete case shows what (.+) explains and where it strains\.", text)
    if match:
        return f"What {match.group(1)} explains, and where it starts to strain"

    match = re.fullmatch(r"The map of (.+) becomes useful once the parts stop doing different work\.", text)
    if match:
        return f"Why {match.group(1)} matters in practice"

    return text


def should_remove_paragraph(text: str) -> bool:
    cleaned = " ".join(text.split())
    return any(pattern.match(cleaned) for pattern in REMOVE_PARAGRAPH_PATTERNS)


def clean_page(path: Path) -> bool:
    original = path.read_text()
    updated = original.replace(f"{AUTO_MARKER}\n", "", 1).replace(AUTO_MARKER, "", 1)
    soup = BeautifulSoup(updated, "html.parser")
    changed = updated != original

    for heading in soup.select("section.article-section--prompt > h2"):
        new_text = normalize_heading_text(heading.get_text(" ", strip=True))
        if new_text != heading.get_text(" ", strip=True):
            heading.clear()
            heading.append(new_text)
            changed = True

    for paragraph in soup.select("section.article-section--prompt > p"):
        classes = set(paragraph.get("class") or [])
        if "article-section__prompt" in classes:
            continue
        text = paragraph.get_text(" ", strip=True)
        if not text:
            continue
        if should_remove_paragraph(text):
            paragraph.decompose()
            changed = True
            continue
        if text.startswith("In plain terms:"):
            new_text = text[len("In plain terms:") :].strip()
            if new_text and new_text != text:
                paragraph.clear()
                paragraph.append(new_text)
                changed = True

    rendered = str(soup)
    rendered = rendered.replace("“ ", "“").replace(" ”", "”").replace('" ', '"').replace(' "', '"')
    rendered = rendered.replace("> Chairs <", ">Chairs<")
    if rendered == original:
        return False
    path.write_text(rendered)
    return True


def main() -> int:
    changed_files = []
    for path in load_batch_paths():
        if clean_page(path):
            changed_files.append(path)
    print(f"Polished {len(changed_files)} batch pages.")
    for path in changed_files:
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
