#!/usr/bin/env python3
"""Revise only the three curator-approved, first-repository site-native baselines.

These are editorial/reconstructed profiles, never recovered WordPress originals.
The immutable baseline controls prompts, response positions, lists and follow-ups.
"""
import argparse
import copy
import hashlib
import json
import subprocess
from collections import Counter
from pathlib import Path
from bs4 import BeautifulSoup, Comment

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'quality/original-source-revisions'
MANIFEST = DATA / 'site-native-baselines-2026-09-21.json'


def fragment(node, value):
    node.clear()
    for child in list(BeautifulSoup(value, 'html.parser').contents):
        node.append(child)


def render(config):
    baseline = next(p for p in json.loads(MANIFEST.read_text())['pages'] if p['pagePath'] == config['pagePath'])
    raw = (ROOT / baseline['committedBaselineSnapshot']).read_bytes()
    assert hashlib.sha256(raw).hexdigest() == baseline['sha256']
    original = BeautifulSoup(raw, 'html.parser')
    shell = subprocess.check_output(['git', 'show', f"{config['shellRevision']}:{baseline['repositoryFile']}"], cwd=ROOT, text=True)
    soup = BeautifulSoup(shell, 'html.parser')
    for node in soup.find_all(string=lambda x: isinstance(x, Comment)):
        if 'AUTO-GENERATED BY scripts/build_archive.py' in node:
            node.replace_with(Comment(' EDITORIALLY MAINTAINED: original-preserving cycle 8; curator-approved site-native baseline '))
    body = soup.select_one('.article-body')
    route = body.select_one('#reader-route').extract()
    future = copy.deepcopy(original.select_one('#future-branches'))
    # Keep current navigation destinations; old placeholder chips become broken
    # tag links when the full builder processes the first-repository markup.
    future.select_one('.tag-row').replace_with(copy.deepcopy(body.select_one('#future-branches .tag-row')))
    quiz = soup.select_one('.quiz-section').extract()
    body.clear()
    intro = soup.new_tag('section', attrs={'class':'article-section','id':'source-texture'})
    fragment(intro, '<h2>Source and context</h2><p>'+config['intro']+'</p><p>This is a site-native editorial/reconstructed profile, not an original WordPress conversation or a response attributable to a particular model. The curator approved its first-repository edition as the baseline. Its four prompts remain verbatim and in order.</p><p><a href="'+baseline['sourceURL']+'">First-repository baseline</a>.</p>')
    body.append(intro)
    body.append(route)
    for n, revision in enumerate(config['sections'], 1):
        section = copy.deepcopy(original.select_one(f'#prompt-{n}'))
        prompt = section.select_one('.article-section__prompt')
        assert prompt.get_text(' ', strip=True) == f"Prompt {n}: {baseline['prompts'][n-1]}"
        fragment(prompt, f'<span>Prompt {n}:</span> <span class="original-prompt-text"></span>')
        prompt.select_one('.original-prompt-text').string = baseline['prompts'][n-1]
        fragment(section.select_one('.article-section__meta'), f'<span class="article-section__number">{n}</span> Site-native editorial response')
        section.h2.string = revision['heading']
        paragraphs = [p for p in section.find_all('p', recursive=False) if p is not prompt]
        # Consolidate repetitive instructions-to-the-writer into substantive prose,
        # leaving the source list, its entry order, and response location intact.
        assert len(paragraphs) == revision['baselineParagraphCount']
        for p in paragraphs:
            p.decompose()
        anchor = section.h2
        for value in revision['paragraphs']:
            p = soup.new_tag('p')
            fragment(p, value)
            anchor.insert_after(p)
            anchor = p
        items = section.find('ol', recursive=False).find_all('li', recursive=False)
        assert len(items) == len(revision['listItems'])
        for k, (node, value) in enumerate(zip(items, revision['listItems']),1):
            fragment(node, value)
            node['data-baseline-item'] = f'{n}.{k}'
        notice = section.select_one('.learning-card')
        if notice:
            items = notice.find_all('li')
            assert len(items) == len(revision['notices'])
            for node, value in zip(items, revision['notices']):
                fragment(node, value)
        else:
            assert not revision.get('notices')
        body.append(section)
    synthesis = copy.deepcopy(original.select_one('#synthesis'))
    synthesis.h2.string = config['synthesisHeading']
    paragraphs = synthesis.find_all('p', recursive=False)
    assert len(paragraphs) == len(config['synthesisParagraphs'])
    for node, value in zip(paragraphs, config['synthesisParagraphs']):
        fragment(node, value)
    notice = synthesis.select_one('.learning-card')
    if notice:
        assert len(notice.find_all('li')) == len(config['synthesisNotices'])
        for node, value in zip(notice.find_all('li'), config['synthesisNotices']):
            fragment(node, value)
    body.append(synthesis)
    questions = quiz.select('.quiz-item')
    assert len(questions) == len(config['quiz']) == 8
    for node, question in zip(questions, config['quiz']):
        node.select_one('.quiz-reset').string = question['question']
        choices = node.select('.quiz-choice')
        assert len(choices) == len(question['options']) == 4
        for k, (choice, value) in enumerate(zip(choices, question['options'])):
            correct = k == question['answer']
            label = choice.label
            feedback = choice.select_one('.quiz-feedback')
            if feedback is None:
                feedback = soup.new_tag('p', attrs={'aria-live':'polite'})
            else:
                feedback.extract()
            label['class'] = ['quiz-option', 'quiz-option--correct' if correct else 'quiz-option--incorrect']
            label.find_all('span', recursive=False)[-1].string = value
            feedback['class'] = ['quiz-feedback','is-correct' if correct else 'is-incorrect']
            feedback.string = ('Correct. ' if correct else 'Not quite. ') + question['explanations'][k]
            choice.append(feedback)
    body.append(quiz)
    refs = soup.new_tag('section', attrs={'class':'article-section','id':'revision-references'})
    fragment(refs, config['references'])
    body.append(refs)
    body.append(future)
    description = config['description']
    soup.select_one('.article-standfirst').string = description
    for name in ['description','og:description','twitter:description']:
        node = soup.find('meta', attrs={'name':name}) or soup.find('meta', attrs={'property':name})
        if node:
            node['content'] = description
    for node in soup.select('meta[property="article:modified_time"]'):
        node['content'] = '2026-09-22'
    for node in soup.select('script[type="application/ld+json"]'):
        data = json.loads(node.string or '{}')
        if data.get('@type') == 'Article':
            data.update(dateModified='2026-09-22', description=description)
            node.string = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
    return '\n'.join(line.rstrip() for line in str(soup).splitlines())+'\n'


def verify(config, rendered):
    baseline = next(p for p in json.loads(MANIFEST.read_text())['pages'] if p['pagePath'] == config['pagePath'])
    source = BeautifulSoup((ROOT / baseline['committedBaselineSnapshot']).read_text(), 'html.parser')
    soup = BeautifulSoup(rendered, 'html.parser')
    assert [x.get_text() for x in soup.select('.original-prompt-text')] == baseline['prompts']
    assert [x.get_text(' ',strip=True) for x in soup.select('.prompt-ledger__text')] == baseline['prompts']
    assert [x.get('id') for x in soup.select('.article-section--prompt')] == [f'prompt-{n}' for n in range(1,5)]
    for n, revision in enumerate(config['sections'],1):
        sec = soup.select_one(f'#prompt-{n}')
        assert [x.get_text(' ',strip=True) for x in sec.find_all('p',recursive=False)[1:]] == [BeautifulSoup(x,'html.parser').get_text(' ',strip=True) for x in revision['paragraphs']]
        assert len(sec.find('ol',recursive=False).find_all('li',recursive=False)) == len(source.select_one(f'#prompt-{n}').find('ol',recursive=False).find_all('li',recursive=False))
        assert [x.get_text() for x in sec.select('[data-baseline-item]')] == [BeautifulSoup(x,'html.parser').get_text() for x in revision['listItems']]
    assert str(source.select_one('#synthesis > ol')) == str(soup.select_one('#synthesis > ol')), 'Original follow-up questions changed'
    assert len(soup.select('.quiz-item')) == 8
    for node,q in zip(soup.select('.quiz-item'),config['quiz']):
        assert node.select_one('.quiz-reset').get_text() == q['question']
        assert [x.find_all('span',recursive=False)[-1].get_text() for x in node.select('.quiz-option')] == q['options']
        assert [x.get_text() for x in node.select('.quiz-feedback')] == [('Correct. ' if k == q['answer'] else 'Not quite. ') + value for k,value in enumerate(q['explanations'])]
        assert len(node.select('.quiz-option--correct')) == 1
        assert node.select('.quiz-option')[q['answer']] == node.select_one('.quiz-option--correct')
    ids=[x['id'] for x in soup.select('[id]')]
    assert all(v==1 for v in Counter(ids).values())
    for a in soup.select('a[href^="#"]'):
        assert soup.find(id=a['href'][1:]), a['href']
    assert 'EDITORIALLY MAINTAINED:' in rendered and 'AUTO-GENERATED BY scripts/build_archive.py' not in rendered
    assert 'not an original WordPress conversation' in soup.get_text()
    return {'pagePath':config['pagePath'],'sourceKind':baseline['sourceKind'],'sourceIsOriginalWordPress':False,'baselineSnapshot':baseline['committedBaselineSnapshot'],'baselineSha256':baseline['sha256'],'originalPrompts':4,'responseSections':4,'promptOrderExact':True,'originalResponseListCounts':[len(x['listItems']) for x in config['sections']],'originalSynthesisQuestionsPreserved':5,'quizQuestions':8,'genericParagraphsConsolidated':sum(x['baselineParagraphCount']-len(x['paragraphs']) for x in config['sections']),'sha256':hashlib.sha256(rendered.encode()).hexdigest()}


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('slug',choices=['al-ghazali','anselm-of-canterbury','arthur-schopenhauer'])
    p.add_argument('--write',action='store_true')
    args=p.parse_args()
    config=json.loads((DATA/(args.slug+'-site-native-edits.json')).read_text())
    result=render(config)
    checks=verify(config,result)
    target=ROOT/config['pagePath'].strip('/')/'index.html'
    if args.write:
        batch=json.loads((ROOT/'quality/editorial-audit-tracker.json').read_text())['currentBatch']['pages']
        assert config['pagePath'] in [p['pagePath'] for p in batch]
        target.write_text(result)
    else:
        assert target.read_text()==result
    print(json.dumps(checks,indent=2))


if __name__=='__main__':
    main()
