#!/usr/bin/env python3
"""Reproduce the Empiricists revision from its full WordPress original.

A fixed repository revision supplies only the site shell. Original response
blocks come exclusively from the committed WordPress snapshot, never the shell.
"""
import argparse
import copy
import hashlib
import json
import subprocess
from collections import Counter
from pathlib import Path

from bs4 import BeautifulSoup, Comment

ROOT = Path(__file__).resolve().parents[1]
PAGE = 'philosophers/empiricists/index.html'
DATA = ROOT / 'quality/original-source-revisions'
SHELL_REV = '4bc27a2da'
MARKER = ' EDITORIALLY MAINTAINED: original-preserving cycle 8; WordPress post 7744 '


def txt(node):
    return node.get_text(' ', strip=True)


def source_sections(soup):
    return [(h, h.find_next_sibling().select(':scope > .wp-block-column')) for h in soup.select('h2')]


def clean(node):
    for el in [node, *node.find_all(True)]:
        el.attrs = {k: v for k, v in el.attrs.items() if k in ('href', 'colspan', 'rowspan')}
    return node


def fragment(soup, html):
    return list(BeautifulSoup(html, 'html.parser').contents)


def make(soup, name, text=None, **attrs):
    node = soup.new_tag(name, attrs=attrs)
    if text is not None:
        node.string = text
    return node


def render():
    source = BeautifulSoup((DATA / 'empiricists-wordpress-7744.html').read_text(), 'html.parser')
    edits = json.loads((DATA / 'empiricists-edits.json').read_text())
    sections = source_sections(source)
    assert len(sections) == 6 and all(len(cols) == 2 for _, cols in sections)
    shell = subprocess.check_output(['git', 'show', f'{SHELL_REV}:{PAGE}'], cwd=ROOT, text=True)
    soup = BeautifulSoup(shell, 'html.parser')
    for node in soup.find_all(string=lambda n: isinstance(n, Comment)):
        if 'AUTO-GENERATED BY scripts/build_archive.py' in node:
            node.replace_with(Comment(MARKER))
    body = soup.select_one('.article-body')
    route = body.select_one('#reader-route').extract()
    future = body.select_one('#future-branches').extract()
    body.clear()
    intro = make(soup, 'section', **{'class':'article-section','id':'source-texture'})
    intro.append(make(soup, 'h2', 'Experience, evidence, and the limits of knowledge'))
    intro.append(make(soup, 'p', 'This conversation moves from an introduction to empiricism through its contributions and leading thinkers, then tests the ideas in two hypothetical dialogues. The original questions and separate ChatGPT and Gemini responses are preserved below, with editorial revisions to the responses.'))
    link = make(soup, 'a', 'Original WordPress post, May 2, 2024', href='http://byteseismic.com/2024/05/02/empiricists/')
    p = make(soup, 'p'); p.append(link); intro.append(p)
    intro.append(make(soup, 'h3', 'Highlights'))
    highlights = make(soup, 'ul')
    for value in [
        'Empiricism gives experience a central role in the formation and testing of knowledge.',
        'Locke includes sensation and reflection; rejecting innate ideas does not mean rejecting mental abilities.',
        'Observable evidence can support claims about things we do not perceive directly.',
        'Experiments and independent checks help distinguish reliable observations from repeated errors.',
        'A posteriori knowledge depends on experience for its justification; a priori and innate are not interchangeable terms.',
    ]:
        highlights.append(make(soup, 'li', value))
    intro.append(highlights); body.append(intro); body.append(route)
    ledger = soup.select_one('.prompt-ledger ol'); ledger.clear()
    for n, (heading, cols) in enumerate(sections, 1):
        prompt = heading.get_text()  # Exact decoded source wording, including 1st-year.
        entry = make(soup, 'li')
        a = make(soup, 'a', **{'class':'prompt-ledger__link','href':f'#prompt-{n}'})
        a.append(make(soup, 'span', str(n), **{'class':'prompt-number','aria-hidden':'true'}))
        a.append(make(soup, 'span', prompt, **{'class':'prompt-ledger__text'}))
        entry.append(a); ledger.append(entry)
        section = make(soup, 'section', **{'class':'article-section article-section--prompt','id':f'prompt-{n}'})
        meta = make(soup, 'div', **{'class':'article-section__meta'})
        meta.append(make(soup, 'span', str(n), **{'class':'prompt-number article-section__number','aria-hidden':'true'}))
        meta.append(make(soup, 'span', 'Original prompt · revised responses'))
        section.append(meta)
        p = make(soup, 'p', **{'class':'article-section__prompt'})
        p.append(make(soup, 'span', f'Prompt {n}:')); p.append(' ')
        p.append(make(soup, 'span', prompt, **{'class':'original-prompt-text'})); section.append(p)
        section.append(make(soup, 'h2', [
            'What empiricism claims', 'Contributions to philosophical thought',
            'Influential empiricists', 'Two conversations with a first-year student',
            'Seven-item quizzes and answers', 'Twelve discussion questions from each response',
        ][n-1]))
        for c, original in enumerate(cols, 1):
            col = clean(copy.deepcopy(original)); col['class'] = ['original-response']
            col['data-source-column'] = str(c)
            nodes = col.find_all(['p', 'li', 'h3'])
            for k, node in enumerate(nodes):
                key = f'{n}.{c}.{k}'
                node['data-source-node'] = key
                if key in edits['replacements']:
                    node.clear()
                    for item in fragment(soup, edits['replacements'][key]):node.append(item)
            if n == 4:
                turns = col.find_all('p', recursive=False)
                lines = make(soup, 'ol', **{'class':'source-dialogue'})
                if c == 1:
                    # Keep all 21 original voices in order, with the closing exchange on line 20.
                    for i in range(20):
                        line = make(soup, 'li'); line.append(turns[i].extract())
                        if i == 19:line.append(turns[20].extract())
                        lines.append(line)
                    col.append(make(soup, 'p', 'Twenty numbered dialogue lines; the final line contains both voices of the closing exchange.'))
                else:
                    for turn in turns:
                        line = make(soup, 'li'); line.append(turn.extract()); lines.append(line)
                    for text in edits['geminiDialogueContinuation']:
                        line = make(soup, 'li'); line.append(make(soup, 'p', text)); lines.append(line)
                col.append(lines)
            # Source headings must sit below the model label in the document outline.
            for h in col.find_all('h3'):h.name = 'h4'
            label = make(soup, 'h3', ['ChatGPT response · revised', 'Gemini response · revised'][c-1])
            col.insert(0, label); section.append(col)
        body.append(section)
    sources = make(soup, 'section', **{'class':'article-section','id':'revision-references'})
    sources.append(make(soup, 'h2', 'Further reading'))
    p = make(soup, 'p', 'For the distinctions about experience, innate ideas, and justification, see ')
    p.append(make(soup, 'a', 'Rationalism vs. Empiricism', href='https://plato.stanford.edu/entries/rationalism-empiricism/'))
    p.append('. For Berkeley’s account of sensible objects and minds, see ')
    p.append(make(soup, 'a', 'George Berkeley', href='https://plato.stanford.edu/entries/berkeley/')); p.append('.')
    sources.append(p); body.append(sources); body.append(future)
    description = 'Explore empiricism through its central claims, contributions, leading thinkers, two dialogues, quizzes, and discussion questions.'
    soup.select_one('.article-standfirst').string = description
    for name in ['description','og:description','twitter:description']:
        node = soup.find('meta', attrs={'name':name}) or soup.find('meta', attrs={'property':name})
        if node:node['content'] = description
    for node in soup.select('meta[property="article:modified_time"]'):node['content'] = '2026-09-07'
    for node in soup.select('script[type="application/ld+json"]'):
        data = json.loads(node.string or '{}')
        if data.get('@type') == 'Article':
            data.update(dateModified='2026-09-07', description=description)
            node.string = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
    return '\n'.join(line.rstrip() for line in str(soup).splitlines()) + '\n'


def verify(rendered):
    source = BeautifulSoup((DATA / 'empiricists-wordpress-7744.html').read_text(), 'html.parser')
    original = source_sections(source)
    soup = BeautifulSoup(rendered, 'html.parser')
    edits = json.loads((DATA / 'empiricists-edits.json').read_text())
    assert [h.get_text() for h, _ in original] == [n.get_text() for n in soup.select('.original-prompt-text')]
    assert [h.get_text() for h, _ in original] == [n.get_text() for n in soup.select('.prompt-ledger__text')]
    preserved = changed = 0
    for n, (_, cols) in enumerate(original, 1):
        section = soup.select_one(f'#prompt-{n}')
        assert len(section.select('.original-response')) == 2
        for c, col in enumerate(cols, 1):
            originals = col.find_all(['p','li','h3'])
            for k, node in enumerate(originals):
                key = f'{n}.{c}.{k}'
                matches = soup.select(f'[data-source-node="{key}"]'); assert len(matches) == 1, key
                actual = txt(matches[0])
                expected = txt(BeautifulSoup(edits['replacements'][key], 'html.parser')) if key in edits['replacements'] else txt(node)
                assert actual == expected, key
                if key in edits['replacements']:changed += 1
                else:preserved += 1
            ids = [x['data-source-node'] for x in section.select(f'.original-response[data-source-column="{c}"] [data-source-node]')]
            assert ids == [f'{n}.{c}.{k}' for k in range(len(originals))], (n,c,'source order')
    assert all(len(x.find_all('li', recursive=False)) == 20 for x in soup.select('.source-dialogue'))
    assert [len(x.find_all('li',recursive=False)) for x in soup.select('#prompt-5 ol')] == [7,7,7,7]
    assert [len(x.find_all('li',recursive=False)) for x in soup.select('#prompt-6 ol')] == [12,12]
    ids = [x['id'] for x in soup.select('[id]')]; assert all(n == 1 for n in Counter(ids).values())
    for a in soup.select('a[href^="#"]'):
        assert soup.find(id=a['href'][1:]), a['href']
    assert MARKER.strip() in rendered and 'AUTO-GENERATED BY scripts/build_archive.py' not in rendered
    return {'pagesReviewed':1,'originalPrompts':6,'modelResponses':12,'originalNodesRetainedVerbatim':preserved,'originalNodesRevised':changed,'dialogueNumberedLines':[20,20],'originalDialogueTurnsPreserved':[21,13],'addedGeminiTurns':7,'quizQuestionCounts':[7,7],'quizAnswerCounts':[7,7],'discussionQuestionCounts':[12,12],'sha256':hashlib.sha256(rendered.encode()).hexdigest()}


def main():
    parser = argparse.ArgumentParser(description=__doc__); parser.add_argument('--write',action='store_true'); args=parser.parse_args()
    result = render(); checks=verify(result)
    if args.write:
        tracker=json.loads((ROOT/'quality/editorial-audit-tracker.json').read_text())
        assert '/philosophers/empiricists/' in [p['pagePath'] for p in tracker['currentBatch']['pages']]
        (ROOT/PAGE).write_text(result)
    else:assert (ROOT/PAGE).read_text() == result, 'Rendered page differs from verified source revision'
    print(json.dumps(checks,indent=2))


if __name__ == '__main__':main()
