#!/usr/bin/env python3
"""Render individually reviewed conversations from immutable WordPress snapshots.

The fixed Git revision supplies site chrome only. Each configuration contains
explicit, source-addressed edits and page-specific review decisions.
"""
import argparse
import copy
import hashlib
import json
import subprocess
from collections import Counter
from pathlib import Path

from bs4 import BeautifulSoup, Comment

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'quality/original-source-revisions'
TAGS = ['p', 'li', 'h3', 'h4']


def text(node):
    return node.get_text(' ', strip=True)


def own_text(node):
    """Exclude nested tracked blocks when counting unchanged source blocks."""
    clone = copy.deepcopy(node)
    for child in clone.find_all(TAGS):
        child.decompose()
    return text(clone)


def sections(source):
    return [(h, h.find_next_sibling().select(':scope > .wp-block-column'))
            for h in source.select('h2')]


def tag(soup, name, value=None, **attrs):
    node = soup.new_tag(name, attrs=attrs)
    if value is not None:
        node.string = value
    return node


def edited_column(original, n, c, config):
    col = copy.deepcopy(original)
    for el in [col, *col.find_all(True)]:
        el.attrs = {k: v for k, v in el.attrs.items()
                    if k in ('href', 'colspan', 'rowspan', 'start')}
    col['class'] = ['original-response']
    col['data-source-column'] = str(c)
    nodes = col.find_all(TAGS)
    for k, node in enumerate(nodes):
        node['data-source-node'] = f'{n}.{c}.{k}'
    for k, node in enumerate(nodes):
        key = f'{n}.{c}.{k}'
        if key in config['replacements']:
            assert not node.find_all(TAGS), ('Replacement would remove source descendants', key)
            node.clear()
            for child in list(BeautifulSoup(config['replacements'][key], 'html.parser').contents):
                node.append(child)
    for h in col.find_all('h4'):
        h.name = 'h5'
    for h in col.find_all('h3'):
        h.name = 'h4'
    starts = config.get('orderedListStarts', {}).get(f'{n}.{c}')
    if starts is not None:
        lists = col.find_all('ol')
        assert len(lists) == len(starts)
        for ol, start in zip(lists, starts):
            ol['start'] = str(start)
    return col


def render(config):
    source = BeautifulSoup((DATA / config['snapshot']).read_text(), 'html.parser')
    original = sections(source)
    assert len(original) == len(config['headings'])
    assert all(len(cols) == len(config['modelLabels']) for _, cols in original)
    shell = subprocess.check_output(['git', 'show', f"{config['shellRevision']}:{config['pageFile']}"], cwd=ROOT, text=True)
    soup = BeautifulSoup(shell, 'html.parser')
    for node in soup.find_all(string=lambda n: isinstance(n, Comment)):
        if 'AUTO-GENERATED BY scripts/build_archive.py' in node:
            node.replace_with(Comment(f" EDITORIALLY MAINTAINED: original-preserving cycle 8; WordPress post {config['wordpressId']} "))
    body = soup.select_one('.article-body')
    # Navigation is site chrome, never a source for responses.
    route = body.select_one('#reader-route').extract()
    future = body.select_one('#future-branches').extract()
    body.clear()
    intro = tag(soup, 'section', **{'class': 'article-section', 'id': 'source-texture'})
    intro.append(tag(soup, 'h2', config['introHeading']))
    intro.append(tag(soup, 'p', config['intro']))
    p = tag(soup, 'p')
    p.append(tag(soup, 'a', config['sourceLabel'], href=config['sourceUrl']))
    intro.append(p)
    body.append(intro)
    body.append(route)
    ledger = soup.select_one('.prompt-ledger ol')
    ledger.clear()
    for n, (heading, cols) in enumerate(original, 1):
        prompt = heading.get_text()
        li = tag(soup, 'li')
        a = tag(soup, 'a', **{'class': 'prompt-ledger__link', 'href': f'#prompt-{n}'})
        a.append(tag(soup, 'span', str(n), **{'class': 'prompt-number', 'aria-hidden': 'true'}))
        a.append(tag(soup, 'span', prompt, **{'class': 'prompt-ledger__text'}))
        li.append(a)
        ledger.append(li)
        section = tag(soup, 'section', **{'class': 'article-section article-section--prompt', 'id': f'prompt-{n}'})
        meta = tag(soup, 'div', **{'class': 'article-section__meta'})
        meta.append(tag(soup, 'span', str(n), **{'class': 'prompt-number article-section__number', 'aria-hidden': 'true'}))
        meta.append(tag(soup, 'span', 'Original prompt · edited responses'))
        section.append(meta)
        p = tag(soup, 'p', **{'class': 'article-section__prompt'})
        p.append(tag(soup, 'span', f'Prompt {n}:'))
        p.append(' ')
        p.append(tag(soup, 'span', prompt, **{'class': 'original-prompt-text'}))
        section.append(p)
        section.append(tag(soup, 'h2', config['headings'][n-1]))
        for c, col in enumerate(cols, 1):
            edited = edited_column(col, n, c, config)
            dialogue = config.get('dialogues', {}).get(f'{n}.{c}')
            if dialogue:
                turns = [edited.select_one(f'[data-source-node="{n}.{c}.{k}"]')
                         for k in dialogue['sourceTurnNodes']]
                lines = tag(soup, 'ol', **{'class': 'source-dialogue'})
                for turn in turns:
                    li = tag(soup, 'li')
                    li.append(turn.extract())
                    lines.append(li)
                for value in dialogue.get('continuation', []):
                    li = tag(soup, 'li')
                    li.append(tag(soup, 'p', value))
                    lines.append(li)
                edited.append(lines)
            label = config['modelLabels'][c-1]
            edited.insert(0, tag(soup, 'h3', label + ' response · editorial edition'))
            section.append(edited)
        body.append(section)
    body.append(future)
    description = config['description']
    soup.select_one('.article-standfirst').string = description
    for name in ['description', 'og:description', 'twitter:description']:
        node = soup.find('meta', attrs={'name': name}) or soup.find('meta', attrs={'property': name})
        if node:
            node['content'] = description
    for node in soup.select('meta[property="article:modified_time"]'):
        node['content'] = config['date']
    for node in soup.select('script[type="application/ld+json"]'):
        data = json.loads(node.string or '{}')
        if data.get('@type') == 'Article':
            data.update(dateModified=config['date'], description=description)
            node.string = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
    return '\n'.join(line.rstrip() for line in str(soup).splitlines()) + '\n'


def verify(config, rendered):
    raw = (DATA / config['snapshot']).read_bytes()
    assert hashlib.sha256(raw).hexdigest() == config['sourceSha256']
    original = sections(BeautifulSoup(raw, 'html.parser'))
    soup = BeautifulSoup(rendered, 'html.parser')
    prompts = [h.get_text() for h, _ in original]
    assert prompts == [n.get_text() for n in soup.select('.original-prompt-text')]
    assert prompts == [n.get_text() for n in soup.select('.prompt-ledger__text')]
    used = set()
    retained = changed = 0
    for n, (_, cols) in enumerate(original, 1):
        for c, col in enumerate(cols, 1):
            expected = edited_column(col, n, c, config)
            actual = soup.select_one(f'#prompt-{n} .original-response[data-source-column="{c}"]')
            actual_nodes = actual.select('[data-source-node]')
            expected_nodes = expected.select('[data-source-node]')
            assert [x['data-source-node'] for x in actual_nodes] == [x['data-source-node'] for x in expected_nodes]
            for old, want, got in zip(col.find_all(TAGS), expected_nodes, actual_nodes):
                key = got['data-source-node']
                assert str(got) == str(want), key
                if key in config['replacements']:
                    used.add(key)
                    changed += 1
                else:
                    assert own_text(old) == own_text(got), key
                    retained += 1
            assert [(x.name, len(x.find_all('li', recursive=False))) for x in col.find_all(['ol', 'ul'])] == [(x.name, len(x.find_all('li', recursive=False))) for x in actual.find_all(['ol', 'ul']) if 'source-dialogue' not in x.get('class', [])]
            assert len(col.find_all('table')) == len(actual.find_all('table'))
            assert [ol.get('start', '1') for ol in expected.find_all('ol')] == [
                ol.get('start', '1') for ol in actual.find_all('ol')
                if 'source-dialogue' not in ol.get('class', [])]
            dialogue = config.get('dialogues', {}).get(f'{n}.{c}')
            if dialogue:
                lines = actual.select_one('.source-dialogue').find_all('li', recursive=False)
                source_count = len(dialogue['sourceTurnNodes'])
                assert [line.select_one('[data-source-node]')['data-source-node']
                        for line in lines[:source_count]] == [
                            f'{n}.{c}.{k}' for k in dialogue['sourceTurnNodes']]
                assert [text(line) for line in lines[source_count:]] == dialogue.get('continuation', [])
    assert used == set(config['replacements']), ('Unused edits', set(config['replacements']) - used)
    checks = {}
    for check in config['countChecks']:
        observed = [len(node.find_all(check['child'], recursive=False)) for node in soup.select(check['selector'])]
        assert observed == check['expected'], (check, observed)
        checks[check['name']] = observed
    ids = [x['id'] for x in soup.select('[id]')]
    assert all(count == 1 for count in Counter(ids).values())
    for a in soup.select('a[href^="#"]'):
        assert soup.find(id=a['href'][1:]), a['href']
    assert 'EDITORIALLY MAINTAINED:' in rendered
    assert 'AUTO-GENERATED BY scripts/build_archive.py' not in rendered
    return {'pagePath': '/' + config['pageFile'].removesuffix('index.html'),
            'sourceSha256': config['sourceSha256'], 'originalPrompts': len(prompts),
            'modelResponses': sum(len(cols) for _, cols in original), 'blocksRetainedVerbatim': retained,
            'blocksExplicitlyRevised': changed, 'promptOrderExact': True,
            'sourceBlockOrderExact': True, 'listAndTableStructuresPreserved': True,
            'formatChecks': checks, 'sha256': hashlib.sha256(rendered.encode()).hexdigest()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('slug')
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    config = json.loads((DATA / f'{args.slug}-edits.json').read_text())
    rendered = render(config)
    result = verify(config, rendered)
    if args.write:
        tracker = json.loads((ROOT / 'quality/editorial-audit-tracker.json').read_text())
        assert result['pagePath'] in [p['pagePath'] for p in tracker['currentBatch']['pages']]
        (ROOT / config['pageFile']).write_text(rendered)
    else:
        assert (ROOT / config['pageFile']).read_text() == rendered
    print(json.dumps(result, indent=2))


if __name__ == '__main__':
    main()
